### ISSUE TITLE
Flink ON Yarn 启动同步任务报错Couldn't deploy Yarn session cluster: java.lang.NullPointerException: Value must not be null  是没有配置kerberos的原因吗

### ISSUE THREAD

**Issue by yakunhuang** [DTStack/Taier#1014]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

环境：
hadoop2.7.5
flink1.12.7

Flink ON Yarn 手动可以启动，也可以提交任务，但是启动时报认证错误，我查询看是hadoop没有配置 kerberos的原因不影响

2023-03-28 17:29:49,654 ERROR org.apache.flink.shaded.curator4.org.apache.curator.ConnectionState [] - Authentication failed

taier中启动同步任务一直等待状态
同步任务【test_mysql2mysql】开始执行
[18:40:01] <info> 已经成功发送执行请求...
[18:40:01] <info> 任务提交成功,名称为: run_sync_task_test_mysql2mysql_1680000060321
[18:40:02] <info> 等待运行.....
[18:40:04] <info> 等待运行.....
[18:40:06] <info> 等待运行.....
一直是等待运行
YARN上没有启动 flinkSessionCluster

flink_monitor.log  中一直重复这个错
:196] - Current role is [Leader] and session start auto is true and Lock path is default_null_flink112/flink_session
2023-03-28 18:44:44.115 [pool-default_null_flink112-flink_yarn_monitor-27-thread-1] ERROR c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:213] - Couldn't deploy Yarn session cluster:
java.lang.NullPointerException: Value must not be null.
        at org.apache.flink.configuration.Configuration.setValueInternal(Configuration.java:758)
        at org.apache.flink.configuration.Configuration.setString(Configuration.java:183)
        at com.dtstack.taier.flink.client.AbstractClientManager.getClusterDescriptor(AbstractClientManager.java:214)
        at com.dtstack.taier.flink.session.client.SessionClientManager.createYarnSessionClusterDescriptor(SessionClientManager.java:352)
        at com.dtstack.taier.flink.session.client.SessionClientManager.startFlinkYarnSession(SessionClientManager.java:200)
        at com.dtstack.taier.flink.session.client.SessionClientManager.startAndGetSessionClusterClient(SessionClientManager.java:167)
        at com.dtstack.taier.flink.session.check.SessionStatusMonitor.retry(SessionStatusMonitor.java:311)
        at com.dtstack.taier.flink.session.check.SessionStatusMonitor.lambda$run$0(SessionStatusMonitor.java:163)
        at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:140)
        at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:238)
        at com.dtstack.taier.flink.session.check.SessionStatusMonitor.run(SessionStatusMonitor.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2023-03-28 18:44:44.115 [pool-default_null_flink112-flink_yarn_monitor-27-thread-1] INFO  c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:168] - FlinkYarnSession launched failed.
2023-03-28 18:45:00.507 [pool-FlinkClient_ClientProxy-25-thread-1] WARN  c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:238] - Flink session cluster is unhealthy, waiting to reboot cluster.
2023-03-28 18:45:00.507 [pool-FlinkClient_ClientProxy-25-thread-1] WARN  com.dtstack.taier.flink.FlinkClient [FlinkClient.java:538] - taskId: 4l6r3m3ucgl0, wait flink session client recover: 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/228486766-491f446a-5c30-47b5-9d4a-cd9667f4528f.png)
集群有绑定队列么
看下这个参数 有队列的属性值吗

**Comment by yakunhuang** [comment]
对Web访问页面进行了清空缓存,再次提交任务后清空
