### ISSUE TITLE
提交一个shell 或 python任务提示 [Component Script is not configured]

### ISSUE THREAD

**Issue by dinglingithub** [DTStack/Taier#1093]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

[17:40:50] <info> 第1条任务开始执行
[17:40:50] <error> com.dtstack.taier.common.exception.TaierDefineException: Component Script is not configured
com.dtstack.taier.common.exception.TaierDefineException: Component Script is not configured
	at com.dtstack.taier.scheduler.server.pluginInfo.ScriptPluginInfoStrategy.convertPluginInfo(ScriptPluginInfoStrategy.java:37)
	at com.dtstack.taier.scheduler.server.pluginInfo.KerberosPluginInfo.configSecurity(KerberosPluginInfo.java:57)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xsaffable** [comment]
![image](https://github.com/DTStack/Taier/assets/34018346/15047236-5b43-4992-b874-5c93863a6ddd)
可以在环境参数这里看一下，默认是 runMode=yarn，没有配置 hadoop 集群的话，可以改为 standalone
