### ISSUE TITLE
[Bug] [Taier-RDB] RDB SQL 执行中 进程重启 任务状态卡死 不结束

### ISSUE THREAD

**Issue by vainhope** [DTStack/Taier#1103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

RDB SQL 执行中 进程重启 任务状态卡死 不结束

### What you expected to happen

RDB SQL 执行中 进程重启 任务状态取消

### How to reproduce

RDB SQL 执行中 重启Taier

### Version

v1.4

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
2023-07-27 16:20:30.367 [pool-mysql_default_default_batch_JobStatusDealerDealJob-21-thread-4] ERROR c.d.taier.scheduler.jobdealer.JobStatusDealer [JobStatusDealer.java:141] - jobId:4m4b6bo1320f
java.lang.IllegalArgumentException: pluginInfo|jobIdentifier is null.
        at com.dtstack.taier.common.client.ClientOperator.checkoutOperator(ClientOperator.java:150)
        at com.dtstack.taier.common.client.ClientOperator.getJobStatus(ClientOperator.java:72)
        at com.dtstack.taier.scheduler.WorkerOperator.getJobStatus(WorkerOperator.java:102)
        at com.dtstack.taier.scheduler.WorkerOperator$$FastClassBySpringCGLIB$$b285a6bd.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at com.dtstack.taier.scheduler.WorkerOperator$$EnhancerBySpringCGLIB$$db0d34f7.getJobStatus(<generated>)
        at com.dtstack.taier.scheduler.jobdealer.JobStatusDealer.dealJob(JobStatusDealer.java:192)
        at com.dtstack.taier.scheduler.jobdealer.JobStatusDealer.lambda$run$1(JobStatusDealer.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
