### ISSUE TITLE
增量同步increColumn信息丢失

### ISSUE THREAD

**Issue by cs3163077** [DTStack/Taier#1105]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

同步任务【增量同步】开始执行
[11:38:27] <info> 已经成功发送执行请求...
[11:38:27] <info> 任务提交成功,名称为: run_sync_task_增量同步_1691033908162
[11:38:28] <info> 等待运行.....
[11:38:30] <info> 等待运行.....
[11:38:32] <info> 等待运行.....
[11:38:33] <info> 等待运行.....
[11:38:33] <error> 
====================Flink日志====================
2023-08-03 11:38:33:org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: increColumn can't be empty when increment is true;

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: increColumn can't be empty when increment is true;

	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:371)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:224)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)
	at com.dtstack.taier.flink.FlinkClient.submitJobWithJar(FlinkClient.java:395)
	at com.dtstack.taier.flink.FlinkClient.submitSyncJob(FlinkClient.java:337)
	at com.dtstack.taier.flink.FlinkClient.lambda$processSubmitJobWithType$1(FlinkClient.java:265)
	at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:140)
	at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:238)
	at com.dtstack.taier.flink.FlinkClient.processSubmitJobWithType(FlinkClient.java:252)
	at com.dtstack.taier.pluginapi.client.AbstractClient.submitJob(AbstractClient.java:57)
	at com.dtstack.taier.common.client.ClientProxy$2.execute(ClientProxy.java:103)
	at com.dtstack.taier.common.client.ClientProxy$2.execute(ClientProxy.java:99)
	at com.dtstack.taier.pluginapi.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:31)
	at com.dtstack.taier.common.client.ClientProxy.lambda$submitJob$1(ClientProxy.java:99)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: increColumn can't be empty when increment is true;

	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormatBuilder.checkFormat(JdbcInputFormatBuilder.java:125)
	at com.dtstack.chunjun.source.format.BaseRichInputFormatBuilder.finish(BaseRichInputFormatBuilder.java:69)
	at com.dtstack.chunjun.connector.jdbc.source.JdbcSourceFactory.createSource(JdbcSourceFactory.java:151)
	at com.dtstack.chunjun.Main.exeSyncJob(Main.java:184)
	at com.dtstack.chunjun.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:354)
	... 19 more

====================任务信息====================
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "password" : "**",
          "startLocation" : "1",
          "increColumn" : "id",
          "initReporter" : true,
          "column" : [ {
            "name" : "id",
            "type" : "bigint"
          }, {
            "name" : "name",
            "type" : "nvarchar"
          }, {
            "name" : "birthday",
            "type" : "nvarchar"
          }, {
            "name" : "ts",
            "type" : "datetime"
          } ],
          "increment" : true,
          "connection" : [ {
            "schema" : "dbo",
            "jdbcUrl" : ["jdbc:jtds:sqlserver://192.168.12.115:9698/text" ],
            "table" : [ "cdc_users" ]
          } ],
          "username" : "sa"
        },
        "name" : "sqlserverreader"
      },
      "writer" : {
        "parameter" : {
          "print" : false
        },
        "name" : "streamwriter"
      }
    } ],
    "setting" : {
      "restore" : {
        "restoreColumnName" : "id"
      },
      "speed" : {
        "bytes" : 0,
        "channel" : 1
      }
    }
  }
}

[11:38:33] <error> 运行失败

### What you expected to happen

增量同步

### How to reproduce

测试脚本
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "password": "***************",
            "increment": true,
            "increColumn": "id",
            "initReporter": true,
            "startLocation": "1",
            "column": [
              {
                "name": "id",
                "type": "bigint"
              },
              {
                "name": "name",
                "type": "nvarchar"
              },
              {
                "name": "birthday",
                "type": "nvarchar"
              },
              {
                "name": "ts",
                "type": "datetime"
              }
            ],
            "connection": [
              {
                "schema": "dbo",
                "jdbcUrl": [
                  "jdbc:jtds:sqlserver://192.168.12.115:9698/text"
                ],
                "table": [
                  "cdc_users"
                ]
              }
            ],
            "username": "sa"
          },
          "name": "sqlserverreader"
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print": false
          }
        }
      }
    ],
    "setting": {
      "restore": {
        "restoreColumnName": "id"
      },
      "speed": {
        "channel": 1,
        "bytes": 0
      }
    }
  }
}

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
com.dtstack.taier.scheduler.server.pipeline.operator.SyncOperatorPipeline#removeIncreConf
增量同步 只有周期调度的是否 才回去设置属性
界面临时运行进行调试测试的时候 会移除增量标识 进行数据验证测试
