### ISSUE TITLE
集群管理-配置yarn报错

### ISSUE THREAD

**Issue by mfgcs** [DTStack/Taier#1112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

通过docker-compose启动taier服务，配置yarn之后测试报错
![image](https://github.com/DTStack/Taier/assets/62247746/4b91f6fb-2795-4920-adfe-0b2d023fb762)
java.lang.reflect.UndeclaredThrowableException
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy213.testCon(Unknown Source)
	at com.dtstack.taier.scheduler.executor.DatasourceOperator.testConnect(DatasourceOperator.java:68)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService.testConnect(ConsoleComponentService.java:1137)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService.testComponentWithResult(ConsoleComponentService.java:1024)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService.testConnect(ConsoleComponentService.java:971)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService$$FastClassBySpringCGLIB$$e484d26.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService$$EnhancerBySpringCGLIB$$865e2d9d.testConnect(<generated>)
	at com.dtstack.taier.develop.controller.console.ComponentController.testConnect(ComponentController.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dtstack.taier.develop.filter.DtRequestWrapperFilter.doFilterInternal(DtRequestWrapperFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: com.dtstack.taier.datasource.api.exception.SourceException: execute method error : Active nodes is empty.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.dtstack.taier.datasource.api.utils.RetryUtils$AsyncRetry.call(RetryUtils.java:183)
	at com.dtstack.taier.datasource.api.utils.RetryUtils$Retry.doRetry(RetryUtils.java:99)
	at com.dtstack.taier.datasource.api.utils.RetryUtils.asyncExecuteWithRetry(RetryUtils.java:65)
	at com.dtstack.taier.datasource.api.proxy.ClientProxyInvocationHandle.invokeMethod(ClientProxyInvocationHandle.java:77)
	at com.dtstack.taier.datasource.api.proxy.ClientProxyInvocationHandle.invoke(ClientProxyInvocationHandle.java:58)
	... 56 more
Caused by: java.lang.Exception: com.dtstack.taier.datasource.api.exception.SourceException: execute method error : Active nodes is empty.
	at com.dtstack.taier.datasource.api.proxy.ClientProxyInvocationHandle.lambda$invokeMethod$0(ClientProxyInvocationHandle.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.dtstack.taier.datasource.api.exception.SourceException: execute method error : Active nodes is empty.
	at com.dtstack.taier.datasource.plugin.yarn.core.client.YarnClientImpl.lambda$getYarnClient$6(YarnClientImpl.java:450)
	at com.dtstack.taier.datasource.plugin.kerberos.core.util.SecurityUtils.login(SecurityUtils.java:80)
	at com.dtstack.taier.datasource.plugin.yarn.core.client.YarnClientImpl.getYarnClient(YarnClientImpl.java:444)
	at com.dtstack.taier.datasource.plugin.yarn.core.client.YarnClientImpl.testCon(YarnClientImpl.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dtstack.taier.datasource.api.proxy.ClientProxyInvocationHandle.lambda$invokeMethod$0(ClientProxyInvocationHandle.java:79)
	... 4 more
Caused by: com.dtstack.taier.datasource.api.exception.SourceException: Active nodes is empty.
	at com.dtstack.taier.datasource.plugin.yarn.core.client.YarnClientImpl.lambda$testCon$0(YarnClientImpl.java:85)
	at com.dtstack.taier.datasource.plugin.yarn.core.client.YarnClientImpl.lambda$getYarnClient$6(YarnClientImpl.java:448)
	... 12 more
Caused by: java.net.ConnectException: Your endpoint configuration is wrong; For more details see:  http://wiki.apache.org/hadoop/UnsetHostnameOrPort
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:824)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:750)
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1495)
	at org.apache.hadoop.ipc.Client.call(Client.java:1437)
	at org.apache.hadoop.ipc.Client.call(Client.java:1347)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy220.getClusterNodes(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getClusterNodes(ApplicationClientProtocolPBClientImpl.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy221.getClusterNodes(Unknown Source)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getNodeReports(YarnClientImpl.java:618)
	at com.dtstack.taier.datasource.plugin.yarn.core.client.YarnClientImpl.lambda$testCon$0(YarnClientImpl.java:80)
	... 13 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:685)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:788)
	at org.apache.hadoop.ipc.Client$Connection.access$3500(Client.java:409)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1552)
	at org.apache.hadoop.ipc.Client.call(Client.java:1383)
	... 30 more

我的hadoop集群版本是3.36
部署了3台服务器，分别是hadoop100，hadoop102，hadoop102，我通过docker-compose启动的taier，docker-compose文件如下

version: '3'
services:
taier-db:
image: dtopensource/taier-mysql:latest
extra_hosts:
- "hadoop100:192.168.3.220"
- "hadoop101:192.168.3.221"
- "hadoop102:192.168.3.222"
environment:
MYSQL_DATABASE: taier
MYSQL_ROOT_PASSWORD: 123456
TZ: Asia/Shanghai
ports:
- 3306:3306
taier-zk:
extra_hosts:
- "hadoop100:192.168.3.220"
- "hadoop101:192.168.3.221"
- "hadoop102:192.168.3.222"
image: zookeeper:3.4.9
taier:
image: dtopensource/taier:latest
extra_hosts:
- "hadoop100:192.168.3.220"
- "hadoop101:192.168.3.221"
- "hadoop102:192.168.3.222"
environment:
ZK_HOST: taier-zk
ZK_PORT: 2181
DB_HOST: taier-db
DB_PORT: 3306
DB_ROOT: root
DB_PASSWORD: 123456
TZ: Asia/Shanghai
ports:
- 8090:8090

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mfgcs** [comment]
我配置sftp用hadoop100都能连通，所以应该不是网络问题！
![image](https://github.com/DTStack/Taier/assets/62247746/2bf8b5a3-bd92-4ec1-9773-9a5e2f2a55a1)

**Comment by vainhope** [comment]
Active nodes is empty 是指Yarn 获取到的runnin个节点为空
确认下yarn 节点是否都是正常的呢

**Comment by trying1996** [comment]
> 我配置sftp用hadoop100都能连通，所以应该不是网络问题！ ![image](https://user-images.githubusercontent.com/62247746/261588026-2bf8b5a3-bd92-4ec1-9773-9a5e2f2a55a1.png)

兄弟，解决了吗，我遇到跟你一样的问题

**Comment by trying1996** [comment]
> 我配置sftp用hadoop100都能连通，所以应该不是网络问题！ ![image](https://user-images.githubusercontent.com/62247746/261588026-2bf8b5a3-bd92-4ec1-9773-9a5e2f2a55a1.png)

兄弟，解决了吗，我跟你遇到一样的问题

**Comment by trying1996** [comment]
是正常的，都是active










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DTStack/Taier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 晚上8:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DTStack/Taier] 集群管理-配置yarn报错 (Issue #1112)





 

 看下集群active node 是否正常

**Comment by trying1996** [comment]
> ![image](https://user-images.githubusercontent.com/18212930/269289767-8558569c-f3f2-48b7-842c-a16e3cc27bd4.png) 看下集群active node 是否正常

进程也是活着的

![image](https://github.com/DTStack/Taier/assets/29252440/b9f6bdd2-ee59-4030-830f-8d3cf4d2734b)
![image](https://github.com/DTStack/Taier/assets/29252440/7b0ea720-2b8c-4676-8d06-5ba91fccb17e)

**Comment by vainhope** [comment]
看下失败原因呢

**Comment by trying1996** [comment]
> ![image](https://user-images.githubusercontent.com/18212930/269289767-8558569c-f3f2-48b7-842c-a16e3cc27bd4.png) 看下集群active node 是否正常

进程也在跑

![image](https://github.com/DTStack/Taier/assets/29252440/a383e554-20a5-4821-a82a-cd6067dda134)
![image](https://github.com/DTStack/Taier/assets/29252440/648ff43a-5037-4473-b29e-489cea6d364b)

**Comment by vainhope** [comment]
Caused by: java.net.ConnectException: Your endpoint configuration is wrong;
确认下rm的端口和ip taier是不是都能ping通

**Comment by trying1996** [comment]
> Caused by: java.net.ConnectException: Your endpoint configuration is wrong; 确认下rm的端口和ip taier是不是都能ping通

可以啊

![image](https://github.com/DTStack/Taier/assets/29252440/dde6b0c7-4abb-4134-81be-db005768b81c)

**Comment by trying1996** [comment]
> Caused by: java.net.ConnectException: Your endpoint configuration is wrong; 确认下rm的端口和ip taier是不是都能ping通

你说的端口是指8088吧？telnet也可以

**Comment by trying1996** [comment]
> Caused by: java.net.ConnectException: Your endpoint configuration is wrong; 确认下rm的端口和ip taier是不是都能ping通

19888的historyserver端口不通，是这样原因吗

**Comment by vainhope** [comment]
和historyserver没有关系 
你看下taier是在bigdata04的机器上吗 
如果是单独的机器 和rm1，rm2的8032端口都通吗 host有配置吗

**Comment by trying1996** [comment]
> 和historyserver没有关系 你看下taier是在bigdata04的机器上吗 如果是单独的机器 和rm1，rm2的8032端口都通吗 host有配置吗

少了些配置，现在可以通了，但又有新问题，页面上会一直有这个提示，并且无法选择任务类型
![image](https://github.com/DTStack/Taier/assets/29252440/e4a17709-666c-49b8-afcc-f50c9e56b8ac)
![image](https://github.com/DTStack/Taier/assets/29252440/6b97f1f6-2e00-4d11-93e1-c6b605b653d9)

**Comment by vainhope** [comment]
https://dtstack.github.io/Taier/docs/functions/multi-cluster
参考组件和任务对应关系配置下计算组件

**Comment by hellomyheart** [comment]
@trying1996 兄弟你的问题最后怎么解决的，我可以看一下你的配置吗？我和你一样，也是Active nodes is empty.

**Comment by hellomyheart** [comment]
@mfgcs 兄弟你的问题最后怎么解决的，我可以看一下你的配置吗？我和你一样，也是Active nodes is empty. 但是hadoop上看是正常的
