### ISSUE TITLE
[Bug] [HiveSql]同样的sql在hue里可以执行成功，但是在taier里通过hivesql脚本执行会报错

### ISSUE THREAD

**Issue by starrywu** [DTStack/Taier#1115]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

(1) 问题描述：
有一个sql在hue里能执行成功，大概耗时50分钟，但同样的sql在taier里通过hivesql脚本连接hiveserver2数据源执行，执行失败，在耗时30多分钟的时候，报错

(2) taier端的日志：
Caused by: org.apache.thrift.transport.TTransportException: java.io.IOException: Stream closed
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.transport.TSaslTransport.readLength(TSaslTransport.java:376)
        at org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:453)
        at org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:435)
        at org.apache.thrift.transport.TSaslClientTransport.read(TSaslClientTransport.java:37)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at org.apache.hive.service.rpc.thrift.TCLIService$Client.recv_GetOperationStatus(TCLIService.java:467)
        at org.apache.hive.service.rpc.thrift.TCLIService$Client.GetOperationStatus(TCLIService.java:454)
        at sun.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hive.jdbc.HiveConnection$SynchronizedHandler.invoke(HiveConnection.java:1438)
        at com.sun.proxy.$Proxy229.GetOperationStatus(Unknown Source)
        at org.apache.hive.jdbc.HiveStatement.waitForOperationToComplete(HiveStatement.java:332)
        ... 11 common frames omitted
Caused by: java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)

(3) yarn端的日志：
2023-09-01 10:42:51,356 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Diagnostics report from attempt_1683883089139_988296_m_000354_0: [2023-09-01 10:42:50.761]Container killed by the ApplicationMaster.
[2023-09-01 10:42:50.816]Container killed on request. Exit code is 143
[2023-09-01 10:42:50.830]Container exited with a non-zero exit code 143.

### What you expected to happen

在taier执行成功

### How to reproduce

准备一个执行时间超过50分钟的hive sql

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiemotongxue** [comment]
如果执行一个较为简单的sql语句是否能成功，比如执行时长非30分钟的，约1分钟内的sql？

**Comment by jiemotongxue** [comment]
@starrywu
