### ISSUE TITLE
[Question][数据同步] flink on yarn的chunjun的路径已配置，但提交任务报空指针异常

### ISSUE THREAD

**Issue by heqxin** [DTStack/Taier#1152]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

单机部署，chunjun版本1.12.8，flink版本1.12.7
<img width="544" alt="微信图片_20240111145249" src="https://github.com/DTStack/Taier/assets/24492148/64a90efc-29ce-4949-bf99-10d686facdb9">

<img width="722" alt="微信图片_20240111145301" src="https://github.com/DTStack/Taier/assets/24492148/493dc2e9-7dde-4b54-a967-30346ac5f05b">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
数据同步默认是session 模式
确认session模式下chunjunDistDir 是否正确 权限是否正常

**Comment by heqxin** [comment]
路径是对的，帮忙看下权限正常吗？
<img width="694" alt="1" src="https://github.com/DTStack/Taier/assets/24492148/d0561442-3e1f-4245-a5dd-79d1fff43e9b">
<img width="494" alt="2" src="https://github.com/DTStack/Taier/assets/24492148/f9e74a34-49cd-4a25-8afc-19d9bc120ee4">

**Comment by vainhope** [comment]
看下taier的启动用户是否用权限读此路径
docker部署 路径是否挂载

**Comment by heqxin** [comment]
是单机部署的，启动用户是root，路径有权限的
<img width="754" alt="3" src="https://github.com/DTStack/Taier/assets/24492148/a38072fe-8aa1-4570-9dc2-2c978209c50f">

**Comment by vainhope** [comment]
![image](https://github.com/DTStack/Taier/assets/18212930/f86d0ac0-c441-4f4c-9936-df3bbdd9b40a)
看报错是chunjunDistDir没取到 你重跑个新任务 或者重启taier试试

**Comment by heqxin** [comment]
重启和新建都失落的，还是那个错误。但我发现，在页面上修改flink的配置参数，点击保存当前组件，日志报错如下：

**Comment by heqxin** [comment]
2024-01-12 10:59:45.179 [http-nio-8090-exec-6] ERROR c.d.t.d.controller.console.UploadController$1 [APITemplate.java:81] - API Error while execute 
com.dtstack.taier.develop.model.exception.InvalidComponentException: 组件 FLINK 错误  version 1.12-on-yarn is not support resource model
	at com.dtstack.taier.develop.model.system.Context.getModelConfig(Context.java:251)
	at com.dtstack.taier.develop.model.part.StandaloneComputePart.getPluginName(StandaloneComputePart.java:41)
	at com.dtstack.taier.develop.model.part.PartImpl.getPluginName(PartImpl.java:119)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService.addOrUpdateComponent(ConsoleComponentService.java:176)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService$$FastClassBySpringCGLIB$$e484d26.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService$$EnhancerBySpringCGLIB$$2134925d.addOrUpdateComponent(<generated>)
	at com.dtstack.taier.develop.controller.console.UploadController$1.process(UploadController.java:122)
	at com.dtstack.taier.develop.controller.console.UploadController$1.process(UploadController.java:81)
	at com.dtstack.taier.common.lang.coc.APITemplate.execute(APITemplate.java:107)
	at com.dtstack.taier.develop.controller.console.UploadController.addOrUpdateComponent(UploadController.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dtstack.taier.develop.filter.DtRequestWrapperFilter.doFilterInternal(DtRequestWrapperFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)

**Comment by vainhope** [comment]
看下taier文档 对应hadoop版本是否支持flink 1.12

**Comment by heqxin** [comment]
请问数据同步默认是session 模式，怎么换成per-job模式？

**Comment by vainhope** [comment]
https://dtstack.github.io/Taier/docs/functions/task/sync#%E7%8E%AF%E5%A2%83%E5%8F%82%E6%95%B0 
参考文档描述
