### ISSUE TITLE
[Question][数据源] 新增数据源不支持kingbase8

### ISSUE THREAD

**Issue by heqxin** [DTStack/Taier#1159]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

taier版本：1.4
新增kingbase8数据源报错：
	
	2024-03-07 14:54:37.899 [http-nio-8090-exec-7] ERROR c.d.t.d.c.datasource.DatasourceAddController$1 [APITemplate.java:81] - API Error while execute 
	java.lang.RuntimeException: com.dtstack.taier.datasource.api.exception.InitializeException: This plugin [kingbase8] is not support.
	at com.dtstack.taier.datasource.api.utils.ClassloaderUtils.executeAndReset(ClassloaderUtils.java:46)
	at com.dtstack.taier.datasource.api.manager.list.ClientManager.registerClient(ClientManager.java:91)
	at com.dtstack.taier.datasource.api.base.ClientCache.getClientByType(ClientCache.java:74)
	at com.dtstack.taier.datasource.api.base.ClientCache.getClient(ClientCache.java:78)
	at com.dtstack.taier.develop.service.datasource.impl.DatasourceService.checkConnectionWithConf(DatasourceService.java:305)
	at com.dtstack.taier.develop.service.datasource.impl.DatasourceService$$FastClassBySpringCGLIB$$56d3bcf9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.dtstack.taier.develop.service.datasource.impl.DatasourceService$$EnhancerBySpringCGLIB$$dc044e5a.checkConnectionWithConf(<generated>)
	at com.dtstack.taier.develop.controller.datasource.DatasourceAddController$1.process(DatasourceAddController.java:129)
	at com.dtstack.taier.develop.controller.datasource.DatasourceAddController$1.process(DatasourceAddController.java:119)
	at com.dtstack.taier.common.lang.coc.APITemplate.execute(APITemplate.java:107)
	at com.dtstack.taier.develop.controller.datasource.DatasourceAddController.testCon(DatasourceAddController.java:131)
	at com.dtstack.taier.develop.controller.datasource.DatasourceAddController$$FastClassBySpringCGLIB$$48423808.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.dtstack.taier.develop.controller.datasource.DatasourceAddController$$EnhancerBySpringCGLIB$$4cd38aa7.testCon(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dtstack.taier.develop.filter.DtRequestWrapperFilter.doFilterInternal(DtRequestWrapperFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
	Caused by: com.dtstack.taier.datasource.api.exception.InitializeException: This plugin [kingbase8] is not support.
	at com.dtstack.taier.datasource.api.manager.list.ClientManager.lambda$registerClient$0(ClientManager.java:95)
	at com.dtstack.taier.datasource.api.utils.ClassloaderUtils.executeAndReset(ClassloaderUtils.java:44)
	... 68 common frames omitted

是需要自己开发吗，是否有开发文档可供参考?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
数据源的开发文档暂时没有 后续会补充
可以直接参考其他datasource 的插件实现 jdbc都差不多

**Comment by vainhope** [comment]
可以参考
https://github.com/DTStack/Taier/pull/1142
