### ISSUE TITLE
启动后提示 忽略 Exit方法调用!

### ISSUE THREAD

**Issue by whiteS18** [DTStack/Taier#1162]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

本地idea启动项目之后提示
```
Exception in thread "main" com.dtstack.taier.common.security.ExitException: 忽略 Exit方法调用!
	at com.dtstack.taier.common.security.NoExitSecurityManager.checkExit(NoExitSecurityManager.java:37)
	at java.lang.Runtime.exit(Runtime.java:101)
	at java.lang.System.exit(System.java:987)
	at com.dtstack.taier.develop.TaierApplication.main(TaierApplication.java:58)
```
断点看到这里没有获取到相关配置信息，但是文档中没有提到需要配置这个，请问还需要什么操作吗？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tlchun** [comment]
这个问题后面怎么解决的
