### ISSUE TITLE
[Bug] [UI] taier-ui 根据README.md 步骤启动报错

### ISSUE THREAD

**Issue by baoyachi** [DTStack/Taier#1182]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

我现在想看下taier-ui的前端界面，发现[Online Preview](http://taier.dtstack.cn/)  报错，

![image](https://github.com/DTStack/Taier/assets/10433001/5d058a82-4e4d-47e5-8e86-4394ee03b3e5)

然后我想 根据Taier/taier-ui/README.md 步骤，构建前端界面也报错。

```bash
➜  taier-ui git:(master) ✗ yarn start
yarn run v1.22.22
warning ../../../package.json: No license field
$ umi dev
Bundle with webpack 5...
Starting the development server...

● Webpack █████████████████████████ building (10%) 0/6 entries 5/6 dependencies 0/5 modules 3 active
 node_modules/.pnpm/monaco-sql-languages@0.9.5/node_modules/monaco-sql-languages/out/esm/hivesql/hivesql.worker.js

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:184161:18)
    at BulkUpdateDecorator.update (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:184062:50)
    at OriginalSource.updateHash (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack-sources2/index.js:1:51038)
    at NormalModule._initBuildHash (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115961:17)
    at handleParseResult (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:116027:10)
    at /Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:116119:4
    at processResult (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115836:11)
    at /Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
    at /Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35132:3
    at iterateNormalLoaders (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34958:10)
    at Array.<anonymous> (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34949:4)
    at runCallbacks (/Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:24341:15)
    at /Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:24514:4
    at /Users/baoyachi/github/Taier/taier-ui/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:33829:16 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.1
✨  Done in 1.98s.
➜  taier-ui git:(master) ✗
```

### What you expected to happen

build ok

### How to reproduce

```bash
➜  taier-ui git:(master) ✗ node -v
v17.9.1
➜  taier-ui git:(master) ✗ yarn build
...
...
```

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jin-sir** [comment]
@baoyachi 
1. 启动报错有可能是 node 版本导致的，降级 node 版本试试
2. 在线预览网站服务暂时被停掉了
