### ISSUE TITLE
配置多集群管理页面中上传zip包失败！

### ISSUE THREAD

**Issue by Su1024** [DTStack/Taier#226]
![image](https://user-images.githubusercontent.com/23012179/155299401-3208c0c1-61db-44e7-ba88-34cb9a10cb05.png)
在配置多集群管理的存储组件、资源组件的配置文件zip包上传失败
![image](https://user-images.githubusercontent.com/23012179/155299566-d380d6a3-38a4-40d9-b533-c6388ec62843.png)
![image](https://user-images.githubusercontent.com/23012179/155299586-003fb3df-45f9-4da2-957e-9cf5a85417bc.png)

日志
```shell
2022-02-23 18:14:40.014 [http-nio-8090-exec-3] ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] [DirectJDKLog.java:175] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.dtstack.taier.common.exception.RdosDefineException: Missing necessary configuration file, maybe the Zip file corrupt, please retry zip files.] with root cause
com.dtstack.taier.common.exception.RdosDefineException: Missing necessary configuration file, maybe the Zip file corrupt, please retry zip files.
	at com.dtstack.taier.develop.service.console.ConsoleComponentService.parseXmlFileConfig(ConsoleComponentService.java:970)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService.config(ConsoleComponentService.java:945)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService$$FastClassBySpringCGLIB$$e484d26.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.dtstack.taier.develop.service.console.ConsoleComponentService$$EnhancerBySpringCGLIB$$777df070.config(<generated>)
	at com.dtstack.taier.develop.controller.console.UploadController.upload(UploadController.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dtstack.taier.develop.filter.DtRequestWrapperFilter.doFilterInternal(DtRequestWrapperFilter.java:87)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jiemotongxue** [comment]
把yarn-site.xml，core-site.xml，hive-site.xml，hdfs-site.xml 文件压缩为一个zip包进行上传，yarn界面和hdfs界面可共用同一个zip包

**Comment by Su1024** [comment]
> 把yarn-site.xml，core-site.xml，hive-site.xml，hdfs-site.xml 文件压缩为一个zip包进行上传，yarn界面和hdfs界面可共用同一个zip包
好的 我再试试

**Comment by jiemotongxue** [comment]
> > 好的 我再试试

**Comment by jiemotongxue** [comment]
> @jiemotongxue 测试了下可以了，不过前端页面有显示不完整的问题

显示问题，数据都是会存储下来的。  之后可以作为前端优化
