### ISSUE TITLE
查询数据异常，聚合类sql报错，配置不存在

### ISSUE THREAD

**Issue by zlj921020** [DTStack/Taier#251]
select * from A没有问题，select count(1) from A就报错，报的是flink conf问题，我没有配置flink和spark，只做了spark thrift的配置
，只用sql还需要配置flink吗

=====================提交日志========================
{"msg_info":"2022-03-02 18:22:04:com.dtstack.taier.common.exception.RdosDefineException: buildPluginInfo error\r
com.dtstack.taier.common.exception.RdosDefineException: buildPluginInfo error\r
 at com.dtstack.taier.scheduler.WorkerOperator.buildPluginInfo(WorkerOperator.java:62)\r
 at com.dtstack.taier.scheduler.WorkerOperator.judgeSlots(WorkerOperator.java:91)\r
 at com.dtstack.taier.scheduler.WorkerOperator$$FastClassBySpringCGLIB$$b285a6bd.invoke(<generated>)\r
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\r
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)\r
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\r
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\r
 at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)\r
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\r
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\r
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)\r
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\r
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\r
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)\r
 at com.dtstack.taier.scheduler.WorkerOperator$$EnhancerBySpringCGLIB$$c94ed81.judgeSlots(<generated>)\r
 at com.dtstack.taier.scheduler.jobdealer.JobSubmitDealer.submitJob(JobSubmitDealer.java:307)\r
 at com.dtstack.taier.scheduler.jobdealer.JobSubmitDealer.lambda$run$0(JobSubmitDealer.java:200)\r
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\r
 at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)\r
 at java.util.concurrent.FutureTask.run(FutureTask.java)\r
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r
 at java.lang.Thread.run(Thread.java:748)\r
Caused by: com.dtstack.taier.common.exception.RdosDefineException: Flink configuration information is empty\r
 at com.dtstack.taier.scheduler.service.ClusterService.buildDeployMode(ClusterService.java:249)\r
 at com.dtstack.taier.scheduler.service.ClusterService.convertPluginInfo(ClusterService.java:223)\r
 at com.dtstack.taier.scheduler.service.ClusterService.pluginInfoJSON(ClusterService.java:90)\r
 at com.dtstack.taier.scheduler.PluginWrapper.wrapperPluginInfo(PluginWrapper.java:50)\r
 at com.dtstack.taier.scheduler.PluginWrapper.wrapperJobClient(PluginWrapper.java:60)\r
 at com.dtstack.taier.scheduler.WorkerOperator.buildPluginInfo(WorkerOperator.java:59)\r
 ... 22 more\r
"}

**Comment by vainhope** [comment]
简单的sql查询是走spark thrift组件直连去查询的
带函数或者复杂的查询 需要配置spark组件
flink 组件是用来支持数据同步任务的 如果不用数据同步 可以不配置flink组件

**Comment by zlj921020** [comment]
spark必须配置2.1的吗？HDP集群自带的可以吗？l另外这些zip在哪里弄
![image](https://user-images.githubusercontent.com/24295496/156353524-0c3e7de1-1473-4246-af16-3fe4a3a693d4.png)

**Comment by vainhope** [comment]
参考这个文档说明
https://dtstack.github.io/Taier/docs/functions/multi-cluster#spark

**Comment by vainhope** [comment]
参考这个文档说明
https://dtstack.github.io/Taier/docs/functions/multi-cluster#spark
