### ISSUE TITLE
taier 运行 sparksql （insert into）异常

### ISSUE THREAD

**Issue by KinoMin** [DTStack/Taier#279]
# 集群环境描述
- cdh6.3.2, 
- Spark2.4.0-cdh6.3.2,
- Hive2.1.1-cdh6.3.2

# 异常日志
以下日志是在yarn上的日志信息
```java
Log Type: stdout

Log Upload Time: 星期五 三月 11 11:17:02 +0800 2022

Log Length: 6507

2022-03-11 11:17:00 INFO  SignalUtils:57 - Registered signal handler for TERM
2022-03-11 11:17:00 INFO  SignalUtils:57 - Registered signal handler for HUP
2022-03-11 11:17:00 INFO  SignalUtils:57 - Registered signal handler for INT
2022-03-11 11:17:00 INFO  SecurityManager:57 - Changing view acls to: yarn,admin
2022-03-11 11:17:00 INFO  SecurityManager:57 - Changing modify acls to: yarn,admin
2022-03-11 11:17:00 INFO  SecurityManager:57 - Changing view acls groups to: 
2022-03-11 11:17:00 INFO  SecurityManager:57 - Changing modify acls groups to: 
2022-03-11 11:17:00 INFO  SecurityManager:57 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(yarn, admin); groups with view permissions: Set(); users  with modify permissions: Set(yarn, admin); groups with modify permissions: Set()
2022-03-11 11:17:00 INFO  ApplicationMaster:57 - ApplicationAttemptId: appattempt_1646906299699_0064_000001
2022-03-11 11:17:00 INFO  YarnRMClient:57 - Registering the ApplicationMaster
2022-03-11 11:17:00 INFO  ConfiguredRMFailoverProxyProvider:100 - Failing over to rm83
2022-03-11 11:17:00 ERROR ApplicationMaster:94 - Uncaught exception: 
org.apache.spark.SparkException: Invalid Spark URL: spark://YarnScheduler@%7B%22logLevel%22%3A%22DEBUG%22%2C%22appName%22%3A%22run_sql_task_1646968206706%22%2C%22sql%22%3A%22UEsDBBQACAgIAENZa1QAAAAAAAAAAAAAAAABAAAAMCstTlUoScxMLbJWyMwrTi0qAVIl%2BQrFBYlF%5Cn2fElqcUlCmWJOaWpxRpGmgoAUEsHCPqA5cAsAAAALAAAAA%3D%3D%5Cn%22%2C%22sparkSessionConf%22%3A%7B%22hive.default.fileformat%22%3A%22orc%22%7D%7D:0
	at org.apache.spark.rpc.RpcEndpointAddress$.apply(RpcEndpointAddress.scala:66)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:134)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runExecutorLauncher(ApplicationMaster.scala:493)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:277)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:805)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:804)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:804)
	at org.apache.spark.deploy.yarn.ExecutorLauncher$.main(ApplicationMaster.scala:836)
	at org.apache.spark.deploy.yarn.ExecutorLauncher.main(ApplicationMaster.scala)
2022-03-11 11:17:00 INFO  ApplicationMaster:57 - Final app status: FAILED, exitCode: 10, (reason: Uncaught exception: org.apache.spark.SparkException: Invalid Spark URL: spark://YarnScheduler@%7B%22logLevel%22%3A%22DEBUG%22%2C%22appName%22%3A%22run_sql_task_1646968206706%22%2C%22sql%22%3A%22UEsDBBQACAgIAENZa1QAAAAAAAAAAAAAAAABAAAAMCstTlUoScxMLbJWyMwrTi0qAVIl%2BQrFBYlF%5Cn2fElqcUlCmWJOaWpxRpGmgoAUEsHCPqA5cAsAAAALAAAAA%3D%3D%5Cn%22%2C%22sparkSessionConf%22%3A%7B%22hive.default.fileformat%22%3A%22orc%22%7D%7D:0
	at org.apache.spark.rpc.RpcEndpointAddress$.apply(RpcEndpointAddress.scala:66)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:134)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runExecutorLauncher(ApplicationMaster.scala:493)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:277)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:805)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:804)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:804)
	at org.apache.spark.deploy.yarn.ExecutorLauncher$.main(ApplicationMaster.scala:836)
	at org.apache.spark.deploy.yarn.ExecutorLauncher.main(ApplicationMaster.scala)
)
2022-03-11 11:17:00 INFO  ApplicationMaster:57 - Unregistering ApplicationMaster with FAILED (diag message: Uncaught exception: org.apache.spark.SparkException: Invalid Spark URL: spark://YarnScheduler@%7B%22logLevel%22%3A%22DEBUG%22%2C%22appName%22%3A%22run_sql_task_1646968206706%22%2C%22sql%22%3A%22UEsDBBQACAgIAENZa1QAAAAAAAAAAAAAAAABAAAAMCstTlUoScxMLbJWyMwrTi0qAVIl%2BQrFBYlF%5Cn2fElqcUlCmWJOaWpxRpGmgoAUEsHCPqA5cAsAAAALAAAAA%3D%3D%5Cn%22%2C%22sparkSessionConf%22%3A%7B%22hive.default.fileformat%22%3A%22orc%22%7D%7D:0
	at org.apache.spark.rpc.RpcEndpointAddress$.apply(RpcEndpointAddress.scala:66)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:134)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runExecutorLauncher(ApplicationMaster.scala:493)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:277)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:805)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:804)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:804)
	at org.apache.spark.deploy.yarn.ExecutorLauncher$.main(ApplicationMaster.scala:836)
	at org.apache.spark.deploy.yarn.ExecutorLauncher.main(ApplicationMaster.scala)
)
2022-03-11 11:17:00 INFO  AMRMClientImpl:484 - Waiting for application to be successfully unregistered.
2022-03-11 11:17:01 INFO  ApplicationMaster:57 - Deleting staging directory hdfs://nameservice1/user/admin/.sparkStaging/application_1646906299699_0064
2022-03-11 11:17:01 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-03-11 11:17:01 INFO  ShutdownHookManager:57 - Shutdown hook called
```

**Comment by xiuzhu9527** [comment]
兼容问题，目前不支持cdh6.3.2
