### ISSUE TITLE
运行mysql同步到hive，任务报错

### ISSUE THREAD

**Issue by zuoinlv** [DTStack/Taier#316]
/data/insight_plugin/ 目录下已经配置相关同步组件：
![image](https://user-images.githubusercontent.com/3855382/160542965-8fae0baf-a644-4acf-99ab-b4acd0664c12.png)

----------------------------------------------------------------------
报错日志：

同步任务【imp_dim_public_adcode_df】开始执行
[13:51:47] <info> 已经成功发送执行请求...
[13:51:47] <info> 任务提交成功,名称为: run_sync_task_imp_dim_public_adcode_df_1648533164455
[13:51:49] <info> 等待运行.....
[13:51:50] <info> 等待运行.....
[13:51:50] <error> 
====================Flink日志====================
2022-03-29 13:52:46:com.dtstack.taier.pluginapi.exception.PluginDefineException: org.apache.flink.client.program.ProgramInvocationException: Could not run job in detached mode. (JobID: 79df4dece28041a4f97dfbe5f393e867)
com.dtstack.taier.pluginapi.exception.PluginDefineException: org.apache.flink.client.program.ProgramInvocationException: Could not run job in detached mode. (JobID: 79df4dece28041a4f97dfbe5f393e867)
	at com.dtstack.taier.flink.FlinkClient.runJobBySession(FlinkClient.java:304)
	at com.dtstack.taier.flink.FlinkClient.submitJobWithJar(FlinkClient.java:254)
	at com.dtstack.taier.flink.FlinkClient.submitSyncJob(FlinkClient.java:633)
	at com.dtstack.taier.flink.FlinkClient.lambda$processSubmitJobWithType$1(FlinkClient.java:185)
	at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:133)
	at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:227)
	at com.dtstack.taier.flink.FlinkClient.processSubmitJobWithType(FlinkClient.java:177)
	at com.dtstack.taier.pluginapi.client.AbstractClient.submitJob(AbstractClient.java:54)
	at com.dtstack.taier.common.client.ClientProxy$2.execute(ClientProxy.java:97)
	at com.dtstack.taier.common.client.ClientProxy$2.execute(ClientProxy.java:93)
	at com.dtstack.taier.pluginapi.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:31)
	at com.dtstack.taier.common.client.ClientProxy.lambda$submitJob$1(ClientProxy.java:93)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.client.program.ProgramInvocationException: Could not run job in detached mode. (JobID: 79df4dece28041a4f97dfbe5f393e867)
	at org.apache.flink.client.ClientUtils.submitJob(ClientUtils.java:156)
	at com.dtstack.taier.flink.FlinkClient.runJobBySession(FlinkClient.java:299)
	... 15 more
Caused by: java.util.concurrent.ExecutionException: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.apache.flink.client.ClientUtils.submitJob(ClientUtils.java:153)
	... 16 more
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$7(RestClusterClient.java:359)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$8(FutureUtils.java:274)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:929)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	... 3 more
Caused by: org.apache.flink.runtime.rest.util.RestClientException: [Internal server error., <Exception on server side:
org.apache.flink.runtime.client.JobSubmissionException: Failed to submit job.
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$internalSubmitJob$3(Dispatcher.java:339)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:36)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 6 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
	at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:152)
	at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:84)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$6(Dispatcher.java:382)
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:34)
	... 7 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Source: mysqlreader -> Sink: hdfswriter': Loading the input/output formats failed: 
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:216)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createExecutionGraph(SchedulerBase.java:256)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:228)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:216)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:120)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:105)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:278)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:266)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:98)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:40)
	at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:146)
	... 10 more
Caused by: java.lang.Exception: Loading the input/output formats failed: 
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:156)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:60)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:212)
	... 20 more
Caused by: java.lang.RuntimeException: Deserializing the input/output formats failed: Could not read the user code wrapper: com.dtstack.flinkx.mysql.format.MysqlInputFormat
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:68)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:153)
	... 22 more
Caused by: org.apache.flink.runtime.operators.util.CorruptConfigurationException: Could not read the user code wrapper: com.dtstack.flinkx.mysql.format.MysqlInputFormat
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:290)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:66)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.dtstack.flinkx.mysql.format.MysqlInputFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:61)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1868)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at java.util.HashMap.readObject(HashMap.java:1409)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:576)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:562)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:550)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:511)
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:288)
	... 24 more

End of exception on server side>]
	at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:390)
	at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$3(RestClient.java:374)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	... 4 more

====================任务信息====================
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "password" : "**",
          "customSql" : "",
          "startLocation" : "",
          "increColumn" : "",
          "column" : [ {
            "name" : "adcode",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "adcode"
          }, {
            "name" : "province",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "province"
          }, {
            "name" : "city",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "city"
          }, {
            "name" : "area",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "area"
          }, {
            "name" : "area_code",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "area_code"
          }, {
            "name" : "postcode",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "postcode"
          }, {
            "name" : "longitude",
            "isPart" : false,
            "type" : "DOUBLE",
            "key" : "longitude"
          }, {
            "name" : "latitude",
            "isPart" : false,
            "type" : "DOUBLE",
            "key" : "latitude"
          }, {
            "name" : "anthony_province",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "anthony_province"
          }, {
            "name" : "anthony_city",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "anthony_city"
          }, {
            "name" : "anthony_area",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "anthony_area"
          }, {
            "name" : "vehicle_no_start",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "vehicle_no_start"
          }, {
            "name" : "update_year",
            "isPart" : false,
            "type" : "INT",
            "key" : "update_year"
          } ],
          "connection" : [ {
            "sourceId" : 2,
            "password" : "**",
            "jdbcUrl" : [ "jdbc:mysql://169.169.171.90:3306/bi" ],
            "type" : 1,
            "table" : [ "adcode" ],
            "username" : "admin"
          } ],
          "sourceIds" : [ 2 ],
          "username" : "admin"
        },
        "name" : "mysqlreader"
      },
      "writer" : {
        "parameter" : {
          "path" : "hdfs://master:8020/user/hive/warehouse/taier.db/dim_public_national_adcode",
          "fileName" : "",
          "hadoopConfig" : {
            "hive.exec.reducers.bytes.per.reducer" : "67108864",
            "hive.optimize.reducededuplication" : "true",
            "metadata" : 0,
            "hive.strict.checks.type.safety" : "true",
            "dfs.replication" : "3",
            "hive.exec.copyfile.maxsize" : "33554432",
            "hive.vectorized.execution.enabled" : "true",
            "hadoop.security.auth_to_local" : "DEFAULT",
            "hive.strict.checks.bucketing" : "true",
            "hive.limit.pushdown.memory.usage" : "0.1",
            "hive.strict.checks.no.partition.filter" : "false",
            "hive.merge.mapredfiles" : "false",
            "hive.vectorized.adaptor.usage.mode" : "chosen",
            "hive.vectorized.use.vector.serde.deserialize" : "false",
            "hive.map.aggr" : "true",
            "spark.dynamicAllocation.minExecutors" : "1",
            "spark.yarn.executor.memoryOverhead" : "462m",
            "hadoop.proxyuser.HTTP.hosts" : "*",
            "hive.smbjoin.cache.rows" : "10000",
            "hadoop.proxyuser.httpfs.hosts" : "*",
            "hive.auto.convert.join" : "true",
            "hive.merge.mapfiles" : "true",
            "version" : "2.7.6",
            "dfs.namenode.acls.enabled" : "false",
            "hive.metastore.execute.setugi" : "true",
            "hadoop.security.group.mapping" : "org.apache.hadoop.security.ShellBasedUnixGroupsMapping",
            "net.topology.script.file.name" : "/etc/hadoop/conf.cloudera.yarn/topology.py",
            "hadoop.ssl.keystores.factory.class" : "org.apache.hadoop.security.ssl.FileBasedKeyStoresFactory",
            "hive.zookeeper.quorum" : "slave1,slave2,slave3",
            "spark.dynamicAllocation.enabled" : "true",
            "typeName" : "yarn2-hdfs2-hadoop2",
            "hive.merge.sparkfiles" : "true",
            "dfs.domain.socket.path" : "/var/run/hdfs-sockets/dn",
            "hadoop.ssl.enabled" : "false",
            "hadoop.proxyuser.hdfs.groups" : "*",
            "dfs.namenode.name.dir" : "file:///soft/dfs/nn",
            "dfs.client.use.datanode.hostname" : "false",
            "hive.compute.query.using.stats" : "false",
            "fs.trash.interval" : "1",
            "spark.dynamicAllocation.initialExecutors" : "1",
            "dfs.client.domain.socket.data.traffic" : "false",
            "hadoop.proxyuser.hive.hosts" : "*",
            "spark.executor.memory" : "2746063257b",
            "hive.vectorized.groupby.checkinterval" : "4096",
            "dfs.blocksize" : "134217728",
            "hive.strict.checks.cartesian.product" : "false",
            "hadoop.security.instrumentation.requires.admin" : "false",
            "hive.map.aggr.hash.percentmemory" : "0.5",
            "io.file.buffer.size" : "65536",
            "hadoop.proxyuser.oozie.hosts" : "*",
            "hive.vectorized.use.checked.expressions" : "true",
            "md5zip" : "59b5cba6682d597068b3e9ae2b76cbfd",
            "hadoop.proxyuser.oozie.groups" : "*",
            "hadoop.proxyuser.yarn.hosts" : "*",
            "hive.vectorized.groupby.flush.percent" : "0.1",
            "dfs.namenode.servicerpc-address" : "master:8022",
            "hive.metastore.client.socket.timeout" : "300",
            "hive.optimize.sort.dynamic.partition" : "false",
            "hadoop.ssl.require.client.cert" : "false",
            "mapred.reduce.tasks" : "-1",
            "dfs.client.read.shortcircuit.skip.checksum" : "false",
            "hive.vectorized.execution.reduce.enabled" : "true",
            "hive.fetch.task.conversion" : "minimal",
            "hive.vectorized.use.vectorized.input.format" : "true",
            "hadoop.security.authorization" : "false",
            "hive.metastore.warehouse.dir" : "/user/hive/warehouse",
            "hive.execution.engine" : "mr",
            "hadoop.proxyuser.httpfs.groups" : "*",
            "hive.strict.checks.orderby.no.limit" : "false",
            "spark.driver.memory" : "966367641b",
            "hive.cbo.enable" : "false",
            "spark.yarn.driver.memoryOverhead" : "102m",
            "hadoop.security.authentication" : "simple",
            "hadoop.proxyuser.hdfs.hosts" : "*",
            "hive.optimize.reducededuplication.min.reducer" : "4",
            "hadoop.proxyuser.hue.hosts" : "*",
            "hive.metastore.uris" : "thrift://master:9083",
            "hadoop.proxyuser.yarn.groups" : "*",
            "hive.server2.use.SSL" : "false",
            "hive.vectorized.input.format.excludes" : "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",
            "hadoop.proxyuser.hue.groups" : "*",
            "io.compression.codecs" : "org.apache.hadoop.io.compress.DefaultCodec,org.apache.hadoop.io.compress.GzipCodec,org.apache.hadoop.io.compress.BZip2Codec,org.apache.hadoop.io.compress.DeflateCodec,org.apache.hadoop.io.compress.SnappyCodec,org.apache.hadoop.io.compress.Lz4Codec",
            "hadoop.proxyuser.hive.groups" : "*",
            "hive.cluster.delegation.token.store.class" : "org.apache.hadoop.hive.thrift.MemoryTokenStore",
            "hive.zookeeper.client.port" : "2181",
            "fs.defaultFS" : "hdfs://master:8020",
            "dfs.client.block.write.locateFollowingBlock.retries" : "7",
            "hadoop.ssl.client.conf" : "ssl-client.xml",
            "hadoop.proxyuser.flume.hosts" : "*",
            "hive.server2.logging.operation.log.location" : "/soft/var/log/hive/operation_logs",
            "hive.merge.size.per.task" : "268435456",
            "dfs.https.port" : "9871",
            "dfs.client.read.shortcircuit" : "false",
            "hive.merge.smallfiles.avgsize" : "16777216",
            "dfs.namenode.http-address" : "master:9870",
            "dfs.datanode.hdfs-blocks-metadata.enabled" : "true",
            "hive.exec.reducers.max" : "1099",
            "hive.fetch.task.conversion.threshold" : "268435456",
            "hadoop.ssl.server.conf" : "ssl-server.xml",
            "hive.auto.convert.join.noconditionaltask.size" : "20971520",
            "hive.server2.logging.operation.enabled" : "true",
            "dfs.https.address" : "master:9871",
            "hive.support.concurrency" : "true",
            "spark.executor.cores" : "4",
            "hive.warehouse.subdir.inherit.perms" : "true",
            "spark.dynamicAllocation.maxExecutors" : "2147483647",
            "hive.optimize.bucketmapjoin.sortedmerge" : "false",
            "hive.server2.enable.doAs" : "true",
            "hadoop.rpc.protection" : "authentication",
            "fs.permissions.umask-mode" : "000",
            "spark.shuffle.service.enabled" : "true",
            "hadoop.proxyuser.flume.groups" : "*",
            "hive.zookeeper.namespace" : "hive_zookeeper_namespace_hive",
            "hadoop.proxyuser.HTTP.groups" : "*"
          },
          "column" : [ {
            "name" : "adcode",
            "index" : 0,
            "isPart" : false,
            "type" : "string",
            "key" : "adcode"
          }, {
            "name" : "province",
            "index" : 1,
            "isPart" : false,
            "type" : "string",
            "key" : "province"
          }, {
            "name" : "city",
            "index" : 2,
            "isPart" : false,
            "type" : "string",
            "key" : "city"
          }, {
            "name" : "area",
            "index" : 3,
            "isPart" : false,
            "type" : "string",
            "key" : "area"
          }, {
            "name" : "area_code",
            "index" : 4,
            "isPart" : false,
            "type" : "string",
            "key" : "area_code"
          }, {
            "name" : "postcode",
            "index" : 5,
            "isPart" : false,
            "type" : "string",
            "key" : "postcode"
          }, {
            "name" : "longitude",
            "index" : 6,
            "isPart" : false,
            "type" : "double",
            "key" : "longitude"
          }, {
            "name" : "latitude",
            "index" : 7,
            "isPart" : false,
            "type" : "double",
            "key" : "latitude"
          }, {
            "name" : "anthony_province",
            "index" : 8,
            "isPart" : false,
            "type" : "string",
            "key" : "anthony_province"
          }, {
            "name" : "anthony_city",
            "index" : 9,
            "isPart" : false,
            "type" : "string",
            "key" : "anthony_city"
          }, {
            "name" : "anthony_area",
            "index" : 10,
            "isPart" : false,
            "type" : "string",
            "key" : "anthony_area"
          }, {
            "name" : "vehicle_no_start",
            "index" : 11,
            "isPart" : false,
            "type" : "string",
            "key" : "vehicle_no_start"
          }, {
            "name" : "update_year",
            "index" : 12,
            "isPart" : false,
            "type" : "int",
            "key" : "update_year"
          } ],
          "defaultFS" : "hdfs://master:8020",
          "connection" : [ {
            "jdbcUrl" : "jdbc:hive2://169.169.171.90:10000/taier",
            "table" : [ "dim_public_national_adcode" ]
          } ],
          "writeMode" : "overwrite",
          "encoding" : "utf-8",
          "fullColumnName" : [ "adcode", "province", "city", "area", "area_code", "postcode", "longitude", "latitude", "anthony_province", "anthony_city", "anthony_area", "vehicle_no_start", "update_year" ],
          "fileType" : "parquet",
          "sourceIds" : [ 1 ],
          "fullColumnType" : [ "string", "string", "string", "string", "string", "string", "double", "double", "string", "string", "string", "string", "int" ]
        },
        "name" : "hdfswriter"
      }
    } ],
    "setting" : {
      "restore" : {
        "maxRowNumForCheckpoint" : 0,
        "isRestore" : false,
        "restoreColumnName" : "",
        "restoreColumnIndex" : 0
      },
      "errorLimit" : {
        "record" : 100
      },
      "speed" : {
        "bytes" : 0,
        "channel" : 1
      }
    }
  }
}

[13:51:50] <info> 运行失败

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/161234326-94aba6f7-64b7-4f67-99f3-d5cf99b0de40.png)
 确认下 flink session 里面的job manager 日志是否有加载到mysql的插件

**Comment by zuoinlv** [comment]
![image](https://user-images.githubusercontent.com/3855382/161366553-e22949d9-3c50-4378-ab74-166d49418d95.png)

flinkx-mysql-reader//flinkx-mysql-writer都有的

**Comment by WTZ468071157** [comment]
使用的flink版本是多少呢？是否与flinkx所依赖的flink版本一致呢？

**Comment by zuoinlv** [comment]
![image](https://user-images.githubusercontent.com/3855382/162141869-2a90f79e-2af1-41ab-8caa-a87abd0338af.png)

flink版本是1.10.3

**Comment by WTZ468071157** [comment]
flink 版本是 1.10.3，但是flinkx 依赖的版本应该还是1.10.1，两者版本不一致，导致flink 在加载flinkx 插件包的时候，出现了class 序列化不一致的问题。
解决方案：降低flink 版本为 1.10.1 ，或者手动升级flinkx版本为1.10.3；

**Comment by zuoinlv** [comment]
把flink降为1.10.1，可以正常运行了。现在报"promethues配置为空"这个警告，怎么拿掉

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/162348306-52039c5f-43af-40b3-81d8-d04c1d2acfa9.png)
prometheusHost
prometheusPort

**Comment by zuoinlv** [comment]
已经解决
