### ISSUE TITLE
执行sparksql任务，报错java.lang.ClassNotFoundException: com.dtstack.taier.sql.main.SqlProxy

### ISSUE THREAD

**Issue by gaoasi** [DTStack/Taier#569]
版本信息：
taier： master
spark：2.4

问题描述：
执行sparksql任务时报错：
![image](https://user-images.githubusercontent.com/43560964/171154206-a7745528-b6f4-4c7e-a704-01ecda87b961.png)

报错详情：

2022-05-31 18:13:47,728 main INFO  [SecurityManager:54] SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(yarn, hive); groups with view permissions: Set(); users  with modify permissions: Set(yarn, hive); groups with modify permissions: Set()
2022-05-31 18:13:47,901 main WARN  [NativeCodeLoader:60] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-05-31 18:13:48,056 main INFO  [ApplicationMaster:54] Preparing Local resources
2022-05-31 18:13:48,636 main WARN  [DomainSocketFactory:116] The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
2022-05-31 18:13:48,751 main INFO  [ApplicationMaster:54] ApplicationAttemptId: appattempt_1640919346293_0111_000001
2022-05-31 18:13:48,762 main INFO  [ApplicationMaster:54] Starting the user application in a separate Thread
2022-05-31 18:13:48,764 main ERROR [ApplicationMaster:91] Uncaught exception: 
java.lang.ClassNotFoundException: com.dtstack.taier.sql.main.SqlProxy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.spark.deploy.yarn.ApplicationMaster.startUserApplication(ApplicationMaster.scala:674)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:461)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:779)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
	at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:778)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:803)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
2022-05-31 18:13:48,768 main INFO  [ApplicationMaster:54] Final app status: FAILED, exitCode: 13, (reason: Uncaught exception: java.lang.ClassNotFoundException: com.dtstack.taier.sql.main.SqlProxy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.spark.deploy.yarn.ApplicationMaster.startUserApplication(ApplicationMaster.scala:674)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:461)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:779)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
	at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:778)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:803)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
)
2022-05-31 18:13:48,774 pool-4-thread-1 INFO  [ApplicationMaster:54] Deleting staging directory hdfs://bmr-cluster/user/hive/.sparkStaging/application_1640919346293_0111
2022-05-31 18:13:48,781 pool-4-thread-1 INFO  [ShutdownHookManager:54] Shutdown hook called

**Comment by gaoasi** [comment]
spark的配置：
![image](https://user-images.githubusercontent.com/43560964/171154628-54af3e9f-26b3-4c37-a922-fbdbbf0e12ff.png)
![image](https://user-images.githubusercontent.com/43560964/171154627-735f4c8b-e750-4300-805d-fb9b0e8b4205.png)
