### ISSUE TITLE
请问能在windows系统上通过代码启动码？

### ISSUE THREAD

**Issue by lesliechueng** [DTStack/Taier#603]
目前启动过程中出现chunjun和flink等配置导致任务无法正常运行的问题，能出一个详细一点的组件依赖部署说明嘛？搜了很久没看到相关说明

**Comment by vainhope** [comment]
https://dtstack.github.io/Taier/docs/functions/component/flink

**Comment by lesliechueng** [comment]
> 看下文档。这个有疑问的地方 我在补充
2022-07-07 09:05:29.121 [pool-default_default_flink112-flink_yarn_monitor-38-thread-1] INFO  c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:171] - Current role is [Follower] and session start auto is true and Lock path is default_default_flink112/flink_session
2022-07-07 09:05:29.121 [pool-default_default_flink112-flink_yarn_monitor-38-thread-1] INFO  c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:143] - FlinkYarnSession launched failed.
2022-07-07 09:05:30.188 [pool-FlinkClient_ClientProxy-39-thread-1] INFO  com.dtstack.taier.flink.FlinkClient [FlinkClient.java:116] - ==> init Flink client
2022-07-07 09:05:30.195 [pool-FlinkClient_ClientProxy-39-thread-1] INFO  com.dtstack.taier.flink.config.PluginConfig [PluginConfig.java:52] - ---------flinkx local plugin dir is: G:\githubProjects\DStack\chunjun-dist
2022-07-07 09:05:30.195 [pool-FlinkClient_ClientProxy-39-thread-1] INFO  com.dtstack.taier.flink.config.PluginConfig [PluginConfig.java:53] - ---------flinkx remote plugin dir is: /DStack/chunjun
2022-07-07 09:05:30.223 [pool-FlinkClient_ClientProxy-39-thread-1] INFO  c.dtstack.taier.flink.client.AbstractClientManager [AbstractClientManager.java:129] - buildYarnClient, init YarnClient!
2022-07-07 09:05:33.533 [pool-FlinkClient_ClientProxy-39-thread-1] INFO  c.dtstack.taier.flink.client.AbstractClientManager [AbstractClientManager.java:118] - cost getYarnClient start-time:1657155933530 end-time:1657155933533, cost:3.
2022-07-07 09:05:33.536 [pool-FlinkClient_ClientProxy-39-thread-1] ERROR c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:161] - 
com.dtstack.taier.pluginapi.exception.PluginDefineException: No flink session found on yarn cluster.
	at com.dtstack.taier.flink.session.client.SessionClientManager.initYarnClusterClient(SessionClientManager.java:229)
	at com.dtstack.taier.flink.session.client.SessionClientManager.startFlinkYarnSession(SessionClientManager.java:159)
	at com.dtstack.taier.flink.session.client.SessionClientManager.startAndGetSessionClusterClient(SessionClientManager.java:142)
	at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:133)
	at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:227)
	at com.dtstack.taier.flink.session.client.SessionClientManager.start(SessionClientManager.java:115)
	at com.dtstack.taier.flink.session.client.SessionClientManager.<init>(SessionClientManager.java:89)
	at com.dtstack.taier.flink.client.ClientManagerBuilder.build(ClientManagerBuilder.java:61)
	at com.dtstack.taier.flink.FlinkClient.init(FlinkClient.java:127)
	at com.dtstack.taier.common.client.ClientProxy$1.execute(ClientProxy.java:73)
	at com.dtstack.taier.common.client.ClientProxy$1.execute(ClientProxy.java:70)
	at com.dtstack.taier.pluginapi.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:31)
	at com.dtstack.taier.common.client.ClientProxy.lambda$init$0(ClientProxy.java:70)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-07-07 09:05:33.537 [pool-FlinkClient_ClientProxy-39-thread-1] INFO  c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:171] - Current role is [Follower] and session start auto is true and Lock path is default_default_flink112/flink_session
2022-07-07 09:05:33.538 [pool-FlinkClient_ClientProxy-39-thread-1] INFO  c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:143] - FlinkYarnSession launched failed.
2022-07-07 09:05:33.539 [pool-FlinkClient_ClientProxy-39-thread-1] WARN  c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:133] - Start a yarn session client monitor [default_default_flink112-flink_yarn_monitor].
2022-07-07 09:05:33.547 [pool-default_default_flink112-flink_yarn_monitor-41-thread-1] WARN  c.d.taier.flink.session.check.SessionStatusMonitor [SessionStatusMonitor.java:286] - ThreadName : pool-default_default_flink112-flink_yarn_monitor-41-thread-1 retry times is 1
2022-07-07 09:05:33.548 [pool-default_default_flink112-flink_yarn_monitor-41-thread-1] WARN  c.d.taier.flink.session.check.SessionStatusMonitor [SessionStatusMonitor.java:287] - ----1 retry Flink yarn-session client ----
2022-07-07 09:05:33.549 [pool-FlinkClient_ClientProxy-39-thread-1] INFO  com.dtstack.taier.flink.FlinkClient [FlinkClient.java:131] - <== init Flink client
2022-07-07 09:05:33.563 [pool-default_default_flink112-flink_yarn_monitor-41-thread-1] INFO  c.dtstack.taier.flink.client.AbstractClientManager [AbstractClientManager.java:118] - cost getYarnClient start-time:1657155933549 end-time:1657155933563, cost:14.
2022-07-07 09:05:33.566 [pool-FlinkClient_ClientProxy-39-thread-2] INFO  c.dtstack.taier.flink.client.AbstractClientManager [AbstractClientManager.java:118] - cost getYarnClient start-time:1657155933551 end-time:1657155933566, cost:15.
2022-07-07 09:05:33.568 [pool-default_default_flink112-flink_yarn_monitor-41-thread-1] ERROR c.d.t.flink.session.client.SessionClientManager [SessionClientManager.java:161] - 
com.dtstack.taier.pluginapi.exception.PluginDefineException: No flink session found on yarn cluster.
	at com.dtstack.taier.flink.session.client.SessionClientManager.initYarnClusterClient(SessionClientManager.java:229)
	at com.dtstack.taier.flink.session.client.SessionClientManager.startFlinkYarnSession(SessionClientManager.java:159)
	at com.dtstack.taier.flink.session.client.SessionClientManager.startAndGetSessionClusterClient(SessionClientManager.java:142)
	at com.dtstack.taier.flink.session.check.SessionStatusMonitor.retry(SessionStatusMonitor.java:293)
	at com.dtstack.taier.flink.session.check.SessionStatusMonitor.lambda$run$0(SessionStatusMonitor.java:145)
	at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:133)
	at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:227)
	at com.dtstack.taier.flink.session.check.SessionStatusMonitor.run(SessionStatusMonitor.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

-------------------------------------------------------------------
报错如上，通过8081可以访问flink服务页面

**Comment by vainhope** [comment]
chunjun用的那个tag 版本呢

**Comment by lesliechueng** [comment]
> chunjun用的那个tag 版本呢

用的1.12.4的版本

**Comment by vainhope** [comment]
建议更新chunjun至1.12.5
1.12.4tag打包有问题 session拉起不起来
https://github.com/DTStack/chunjun/pull/905/files
