### ISSUE TITLE
任务提交至调度： “任务提交异常：null“

### ISSUE THREAD

**Issue by flyysoul** [DTStack/Taier#676]
**建议先去浏览下文档和部署常见问题**
[快速开始](https://dtstack.github.io/Taier/)
[部署常见问题](https://github.com/DTStack/Taier/issues/260)

**版本**
tag:v1.2.0

**场景描述**
任务配置完依赖后提交至调度，后端接口报null

**日志信息或数据信息**
```log
2022-08-04 18:12:07.213 [http-nio-8090-exec-5] ERROR c.d.t.d.controller.develop.DevelopTaskController$3 [APITemplate.java:63] - API Error while execute
com.dtstack.taier.common.exception.RdosDefineException: 任务提交异常：null
        at com.dtstack.taier.develop.service.develop.impl.DevelopTaskService.publishTaskInfo(DevelopTaskService.java:509)
        at com.dtstack.taier.develop.service.develop.impl.DevelopTaskService.publishTask(DevelopTaskService.java:405)
        at com.dtstack.taier.develop.service.develop.impl.DevelopTaskService$$FastClassBySpringCGLIB$$110f35e.invoke(<generated>)
...
Caused by: java.lang.NullPointerException: null
        at com.dtstack.taier.develop.service.develop.impl.DevelopTaskService.buildScheduleTaskShadeDTO(DevelopTaskService.java:619)
        at com.dtstack.taier.develop.service.develop.impl.DevelopTaskService.publishTaskInfo(DevelopTaskService.java:502)
        ... 61 common frames omitted
```
**相关代码**
1. 调用：
https://github.com/DTStack/Taier/blob/c5a8622e1f3f13e43e99878c30c5673e269a7d41/taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopTaskService.java#L502
2. 源头
https://github.com/DTStack/Taier/blob/c5a8622e1f3f13e43e99878c30c5673e269a7d41/taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopTaskService.java#L619

**提示的异常或者没有达到的效果**
好像有依赖的任务提交调度就会触发这一步异常。
**欢迎提交对应修复的pr**
(￣┰￣*)ゞ还没学会怎么提pr

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/182988925-cd9b1e6e-ecec-4f43-9230-b95850afecd7.png) 这个地方写的有问题
https://chinese.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github/
可以参考一些pr的文章 尝试提下pr
@flyysoul
