### ISSUE TITLE
flinksql：单流滑动窗口报错

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/Taier#692]
kafka消息：
{"message": {"schema": "test","opTime": 1653623501000,"before": {},"after": {"col1": "5","col2": 2.3},"type": "INSERT","table": "src_test","ts": 6935799661563351040}}
-------------------------------------------------------------------------
kafka2mysql 脚本：
CREATE TABLE sumsrc(
    message ROW < `test` varchar,
    `src_test` varchar,
    after ROW < col1 varchar,
    col2 double >>,
    proc_time AS PROCTIME() 
 )WITH(
    'properties.bootstrap.servers'='node2:9092',
    'connector'='kafka-x',
    'scan.parallelism'='1',
    'format'='json',
    'topic'='danliu_gundongchuangkou',
    'scan.startup.mode'='latest-offset'
 );

CREATE TABLE sumsink(
    totalsale double,
    hops timestamp,
    hop timestamp
 )WITH(
    'password'='****',
    'connector'='mysql-x',
    'sink.buffer-flush.interval'='1000',
    'sink.all-replace'='false',
    'sink.buffer-flush.max-rows'='100',
    'table-name'='danliu_gundongchuangkou',
    'sink.parallelism'='1',
    'url'='jdbc:mysql://xxx:33061/test',
    'username'='root'
 );

insert        
into
    sumsink
    SELECT
        SUM(col2) AS totalsale,
        HOP_START(proc_time,INTERVAL '30' SECOND, INTERVAL '1' MINUTE) AS hops,
        HOP_END(proc_time,INTERVAL '30' SECOND, INTERVAL '1' MINUTE) AS hope
    FROM
        sumsrc      
    GROUP BY
        HOP(proc_time,INTERVAL '30' SECOND, INTERVAL '1' MINUTE);
-------------------------------------------------------------------------------------------

异常信息：

org.apache.flink.streaming.runtime.tasks.AsynchronousException: Caught exception while processing timer.
	at org.apache.flink.streaming.runtime.tasks.StreamTask$StreamTaskAsyncExceptionHandler.handleAsyncException(StreamTask.java:1214) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.handleAsyncException(StreamTask.java:1190) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invokeProcessingTimeCallback(StreamTask.java:1329) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$null$17(StreamTask.java:1318) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:317) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:189) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:619) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:583) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:758) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:573) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
Caused by: org.apache.flink.streaming.runtime.tasks.TimerException: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
	... 11 more
Caused by: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:88) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:50) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.table.runtime.operators.window.AggregateWindowOperator.collect(AggregateWindowOperator.java:188) ~[flink-table-blink_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.table.runtime.operators.window.AggregateWindowOperator.emitWindowResult(AggregateWindowOperator.java:181) ~[flink-table-blink_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.table.runtime.operators.window.WindowOperator.onProcessingTime(WindowOperator.java:404) ~[flink-table-blink_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.InternalTimerServiceImpl.onProcessingTime(InternalTimerServiceImpl.java:284) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invokeProcessingTimeCallback(StreamTask.java:1327) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	... 10 more
Caused by: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:88) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at StreamExecCalc$167.processElement(Unknown Source) ~[?:?]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:50) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.table.runtime.operators.window.AggregateWindowOperator.collect(AggregateWindowOperator.java:188) ~[flink-table-blink_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.table.runtime.operators.window.AggregateWindowOperator.emitWindowResult(AggregateWindowOperator.java:181) ~[flink-table-blink_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.table.runtime.operators.window.WindowOperator.onProcessingTime(WindowOperator.java:404) ~[flink-table-blink_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.InternalTimerServiceImpl.onProcessingTime(InternalTimerServiceImpl.java:284) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invokeProcessingTimeCallback(StreamTask.java:1327) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	... 10 more
Caused by: com.dtstack.flinkx.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
	at com.dtstack.flinkx.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105) ~[flinkx-core-1.12_release.jar:?]
	at com.dtstack.flinkx.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79) ~[flinkx-core-1.12_release.jar:?]
	at com.dtstack.flinkx.dirty.manager.DirtyManager.collect(DirtyManager.java:140) ~[flinkx-core-1.12_release.jar:?]
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:430) ~[flinkx-core-1.12_release.jar:?]
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:448) ~[flinkx-core-1.12_release.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_211]
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:448) ~[flinkx-core-1.12_release.jar:?]
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:404) ~[flinkx-core-1.12_release.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_211]
	... 1 more
--------------------------------------------------------------------------------------------------------

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/183901539-02264279-2dbe-4d3a-814f-35860ccb139f.png)
存在zang脏数据

**Comment by momisabuilder** [comment]
sink表中的字段是hop，mysql目标表是hope，二者保持一致即可
