### ISSUE TITLE
[Bug] [taier-scheduler] 增量同步任务没有把startLocation和endLocation指标写入prometheus

### ISSUE THREAD

**Issue by gzusgw** [DTStack/Taier#760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

配置mysql到hive的增量同步任务，指定增量字段类型为int,perJob模式运行，taier没有把startLocation和endLocation指标写入prometheus，每次同步依然是全量同步，但是chunjun本地local模式测试可以将startLocation和endLocation指标写入prometheus

### What you expected to happen

增量同步任务可以实现增量同步

### How to reproduce

配置msyql到hive的增量同步任务，指定增量字段为int类型，任务json如下：
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "password": "Pwd@1234_Cmict",
            "startLocation": "",
            "increColumn": "test_int",
            "column": [
              {
                "name": "test_int",
                "type": "INT",
                "key": "test_int"
              },
              {
                "name": "test_float",
                "type": "FLOAT",
                "key": "test_float"
              },
              {
                "name": "test_double",
                "type": "DOUBLE",
                "key": "test_double"
              },
              {
                "name": "test_varchar",
                "type": "VARCHAR",
                "key": "test_varchar"
              },
              {
                "name": "test_char",
                "type": "CHAR",
                "key": "test_char"
              }
            ],
            "connection": [
              {
                "sourceId": 1,
                "password": "Pwd@1234_Cmict",
                "jdbcUrl": [
                  "jdbc:mysql://10.136.106.163:33061/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE"
                ],
                "type": 1,
                "table": [
                  "mysql_test_1"
                ],
                "username": "root"
              }
            ],
            "splitPk": "",
            "sourceIds": [
              1
            ],
            "username": "root"
          },
          "name": "mysqlreader"
        },
        "writer": {
          "parameter": {
            "msg": "",
            "fileName": "",
            "column": [
              {
                "name": "test_int",
                "index": 0,
                "isPart": false,
                "type": "int",
                "key": "test_int"
              },
              {
                "name": "test_float",
                "index": 1,
                "isPart": false,
                "type": "float",
                "key": "test_float"
              },
              {
                "name": "test_double",
                "index": 2,
                "isPart": false,
                "type": "double",
                "key": "test_double"
              },
              {
                "name": "test_varchar",
                "index": 3,
                "isPart": false,
                "type": "string",
                "key": "test_varchar"
              },
              {
                "name": "test_char",
                "index": 4,
                "isPart": false,
                "type": "string",
                "key": "test_char"
              }
            ],
            "writeMode": "append",
            "fieldDelimiter": "\u0001",
            "encoding": "utf-8",
            "fullColumnName": [
              "test_int",
              "test_float",
              "test_double",
              "test_varchar",
              "test_char",
              "test_datetime"
            ],
            "partitionType": 0,
            "path": "hdfs://cmict/warehouse/tablespace/managed/hive/tar",
            "hadoopConfig": {
              "hadoop.security.authentication": "kerberos",
              "dfs.nameservices": "cmict",
              "sftpConf": {
                "maxWaitMillis": "3600000",
                "minIdle": "16",
                "auth": "1",
                "isUsePool": "true",
                "typeName": "dummy",
                "versionName": "",
                "version": "",
                "timeout": "10000",
                "path": "/data/sftp",
                "password": "Chaonao@0802",
                "maxIdle": "16",
                "port": "22",
                "maxTotal": "16",
                "host": "10.136.106.163",
                "fileTimeout": "300000",
                "username": "root"
              },
              "java.security.krb5.conf": "krb5.conf",
              "principal": "hive/node2@KRB.COM",
              "dfs.namenode.rpc-address.cmict.nn1": "node1:8020",
              "remoteDir": "/data/sftp/DsCenter_3",
              "dfs.namenode.rpc-address.cmict.nn2": "node2:8020",
              "dfs.ha.namenodes.cmict": "nn1,nn2",
              "hadoop.security.authorization": "true",
              "principalFile": "hive.service.keytab",
              "kerberosDir": "DsCenter_3",
              "dfs.client.use.datanode.hostname": "true",
              "dfs.client.failover.proxy.provider.cmict": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"
            },
            "jdbcUrl": "jdbc:hive2://node1:2181,node2:2181,node3:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2",
            "defaultFS": "hdfs://cmict",
            "connection": [
              {
                "jdbcUrl": "jdbc:hive2://node1:2181,node2:2181,node3:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2",
                "table": [
                  "tar"
                ]
              }
            ],
            "interval": 0,
            "table": "tar",
            "fileType": "text",
            "fullColumnType": [
              "int",
              "float",
              "double",
              "string",
              "string",
              "timestamp"
            ],
            "charsetName": "utf-8",
            "username": "hive"
          },
          "name": "hdfswriter"
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
        "readerChannel": 1,
        "writerChannel": 1,
        "bytes": -1048576
      },
      "restore": {
        "isRestore": false,
        "isStream": false
      }
    }
  }
}

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gzusgw** [comment]
flink web ui中可以看到这两个指标，但是没有写入到prometheus

**Comment by ColdStrangerChen** [comment]
配置flink任务，向导模式与脚本模式检查语法报以下错误


[15:51:56] <info> 语法检查开始
[15:51:56] <error> org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "8s"
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "8s"
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:371)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:224)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)
	at com.dtstack.taier.flink.FlinkClient.grammarCheck(FlinkClient.java:1094)
	at com.dtstack.taier.common.client.ClientProxy.lambda$null$18(ClientProxy.java:347)
	at com.dtstack.taier.pluginapi.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:31)
	at com.dtstack.taier.common.client.ClientProxy.lambda$grammarCheck$19(ClientProxy.java:347)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "8s"
	at java.net.URLDecoder.decode(URLDecoder.java:194)
	at com.dtstack.chunjun.Main.main(Main.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:354)
	... 12 more

[15:51:56] <error> 语法检查失败！

**Comment by ColdStrangerChen** [comment]
配置flink任务，向导模式与脚本模式检查语法报以下错误

[15:51:56] 语法检查开始
[15:51:56] org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "8s"
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "8s"
at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:371)
at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:224)
at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)
at com.dtstack.taier.flink.FlinkClient.grammarCheck(FlinkClient.java:1094)
at com.dtstack.taier.common.client.ClientProxy.lambda$null$18(ClientProxy.java:347)
at com.dtstack.taier.pluginapi.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:31)
at com.dtstack.taier.common.client.ClientProxy.lambda$grammarCheck$19(ClientProxy.java:347)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "8s"
at java.net.URLDecoder.decode(URLDecoder.java:194)
at com.dtstack.chunjun.Main.main(Main.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.flink.client.program.PackagedProgram.callMainMethod(P

**Comment by vainhope** [comment]
@ColdStrangerChen flink sql内容能贴一下么
