### ISSUE TITLE
脚本模式运行同步任务 ftp -> mysql] Bug title判断文件类型逻辑好像有bug

### ISSUE THREAD

**Issue by itWMdeveloping** [DTStack/Taier#765]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

脚本模式运行同步任务 ftp -> mysql
ftp选择xlsx和xls后缀的excel文件报错文件类型不支持，debug进到chunjun源码里是支持excel文件、csv、和txt三种格式的，
但是判断方式是根据文件后缀名和枚举类名称比较，我觉得比较方式应该不对，因为csv和txt文件后缀和文件类型同名，而Excel文件后缀名和文件类型（即枚举名）不一致，所以选excel文件时匹配不上报错不支持
![image](https://user-images.githubusercontent.com/43467953/192423229-534aff6c-8df1-4a91-9350-80c6c427d5be.png)

另外我把一个已经同步成功到mysql表的csv文件重新另存为指标分隔符模式的txt文件，再进行同步，数据同步到mysql没有区分列，txt文件虽然有制表分隔符把每列数据隔开，但同步到数据库所有列合并成了一列全部同步到了mysql第一个字段，也就是说数据同步txt文件应该写成哪种格式可以正确识别出分隔的每一列
![image](https://user-images.githubusercontent.com/43467953/192423342-f19b096e-8f19-4af0-af7c-81e90610c668.png)
另外可以支持json格式的文件类型吗

### What you expected to happen

excel文件和txt同步成功

### How to reproduce

 脚本模式选择ftp的文件同步到mysql

### Version

v1.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiemotongxue** [comment]
@itWMdeveloping   第一个问题，ftp-mysql的**报错信息** 和 **任务文本**贴下。

**Comment by itWMdeveloping** [comment]
{
  "job":{
    "content":[
      {
        "reader":{
          "parameter":{
            "path":"/testFile/as.xlsx",
            "protocol":"ftp",
            "port":21,
            "isFirstLineHeader":false,
            "host":"ftp.xxxxxx.com",
            "column":[
              {
                "index":0,
                "type":"string",
                "name": "c1"
              },
              {
                "index":1,
                "type":"string",
                "name": "c2"
              }
            ],
            "password":"xxxxxx",
            "fieldDelimiter":",",
            "encoding":"utf-8",
            "username":"xxxxxx"
          },
          "name":"ftpreader"
        },
        "writer":{
          "name": "mysqlwriter",
		  "parameter": {
		    "username": "xxxx",
		    "password": "xxxxx",
		    "connection": [
			  {
			    "jdbcUrl": "jdbc:mysql://host:3306/test?useSSL=false",
			    "table": [
				  "sheet"
			    ]
			  }
		    ],
		    "writeMode": "insert",
		    "column": [
			  {
			    "name": "nam",
			    "type": "string"
			  },
			  {
			    "name": "desc",
			    "type": "string"
			  }
		    ]
		  }
        }
      }
    ],
    "setting":{
      "restore":{
        "maxRowNumForCheckpoint":0,
        "isRestore":false,
        "restoreColumnName":"",
        "restoreColumnIndex":0
      },
      "errorLimit":{
        "record":100
      },
      "speed":{
        "bytes":0,
        "channel":1
      }
    }
  }
}

报错：
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:118)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:80)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:233)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:224)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:215)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:666)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:89)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:446)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: No enum constant com.dtstack.flinkx.connector.ftp.client.FileType.XLSX
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.dtstack.flinkx.connector.ftp.client.FileType.valueOf(FileType.java:11)
	at com.dtstack.flinkx.connector.ftp.client.FileType.fromString(FileType.java:22)
	at com.dtstack.flinkx.connector.ftp.client.FileReadClientFactory.create(FileReadClientFactory.java:36)
	at com.dtstack.flinkx.connector.ftp.source.FtpSeqBufferedReader.nextStream(FtpSeqBufferedReader.java:113)
	at com.dtstack.flinkx.connector.ftp.source.FtpSeqBufferedReader.readLine(FtpSeqBufferedReader.java:79)
	at com.dtstack.flinkx.connector.ftp.source.FtpInputFormat.reachedEnd(FtpInputFormat.java:156)
	at com.dtstack.flinkx.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:131)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)

**Comment by jiemotongxue** [comment]
@itWMdeveloping 
注意：使用chunjun 的 tag  1.12.5进行测试；下次验证脚本模式的时候，可以先在chunjun验证通过后再在taier上创建任务，调试的时候效率会更高。

解决方案：协议选择sftp，fileType选择excel，如下图：
![image](https://user-images.githubusercontent.com/16730029/192776639-6b4d8eeb-c178-4ca4-8fa0-48236e03cc08.png)

测试示例：
![image](https://user-images.githubusercontent.com/16730029/192777220-5be3a83a-64be-4e48-8ffc-7e32d302ff4a.png)
![image](https://user-images.githubusercontent.com/16730029/192777273-8fdccae9-3a91-48c4-94aa-830a7d4ca3b1.png)
