### ISSUE TITLE
Flink-standalone组件下数据同步报错

### ISSUE THREAD

**Issue by Sejon** [DTStack/Taier#869]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### MySQL数据同步执行报错
**Flink版本**
v1.12.7
**chunjun版本**
v1.12-SNAPSHOT
**配置内容**
![image](https://user-images.githubusercontent.com/33147746/200775278-98b90106-9ac3-4ebb-b74f-cb33816b0d6c.png)
**报错日志**
`同步任务【数据同步测试】开始执行
[15:10:22] <info> 已经成功发送执行请求...
[15:10:22] <info> 任务提交成功,名称为: run_sync_task_数据同步测试_1667977822889
[15:10:24] <info> 等待运行.....
[15:10:25] <info> 等待运行.....
[15:10:27] <info> 等待运行.....
[15:10:55] <info> 读取记录数:	0  读取字节数:	0  读取速率:	0B/S  写入记录数:	0  写入字节数:	0  写入速率:	0B/S  错误记录数:	0  
[15:10:57] <info> 等待运行.....
[15:11:25] <error> 读取记录数:	0  读取字节数:	0  读取速率:	0B/S  写入记录数:	0  写入字节数:	0  写入速率:	0B/S  错误记录数:	0  
====================Flink日志====================
org.apache.flink.runtime.client.JobInitializationException: Could not instantiate JobManager.
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Source: mysqlsourcefactory -> Sink: mysqlsinkfactory': Loading the input/output formats failed: 
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:293)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createExecutionGraph(SchedulerBase.java:322)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:276)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:249)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:133)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:111)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:342)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:327)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:95)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:39)
	at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:163)
	at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:86)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:472)
	... 4 more
Caused by: java.lang.Exception: Loading the input/output formats failed: 
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:172)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:57)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:289)
	... 16 more
Caused by: java.lang.RuntimeException: Deserializing the input/output formats failed: Could not read the user code wrapper: unexpected exception type
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:69)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:168)
	... 18 more
Caused by: org.apache.flink.runtime.operators.util.CorruptConfigurationException: Could not read the user code wrapper: unexpected exception type
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:307)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:66)
	... 19 more
Caused by: java.io.IOException: unexpected exception type
	at java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1751)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1281)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2245)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at java.util.ArrayList.readObject(ArrayList.java:799)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2345)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at java.util.HashMap.readObject(HashMap.java:1419)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2345)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:615)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:600)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:587)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:541)
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:304)
	... 20 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:230)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1275)
	... 69 more
Caused by: java.lang.ClassCastException: com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter cannot be cast to com.dtstack.chunjun.converter.AbstractRowConverter
	at com.dtstack.chunjun.converter.AbstractRowConverter.$deserializeLambda$(AbstractRowConverter.java:54)
	... 78 more

2022-11-09 15:10:27:submit job is success
====================任务信息====================
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "password" : "**",
          "startLocation" : "",
          "increColumn" : "",
          "column" : [ {
            "name" : "id",
            "type" : "BIGINT",
            "key" : "id"
          }, {
            "name" : "name",
            "type" : "VARCHAR",
            "key" : "name"
          }, {
            "name" : "pic",
            "type" : "VARCHAR",
            "key" : "pic"
          }, {
            "name" : "product_sn",
            "type" : "VARCHAR",
            "key" : "product_sn"
          }, {
            "name" : "delete_status",
            "type" : "INT",
            "key" : "delete_status"
          }, {
            "name" : "publish_status",
            "type" : "INT",
            "key" : "publish_status"
          }, {
            "name" : "new_status",
            "type" : "INT",
            "key" : "new_status"
          }, {
            "name" : "recommand_status",
            "type" : "INT",
            "key" : "recommand_status"
          }, {
            "name" : "verify_status",
            "type" : "INT",
            "key" : "verify_status"
          }, {
            "name" : "sort",
            "type" : "INT",
            "key" : "sort"
          }, {
            "name" : "sale",
            "type" : "INT",
            "key" : "sale"
          }, {
            "name" : "price",
            "type" : "DECIMAL",
            "key" : "price"
          }, {
            "name" : "promotion_price",
            "type" : "DECIMAL",
            "key" : "promotion_price"
          }, {
            "name" : "description",
            "type" : "TEXT",
            "key" : "description"
          }, {
            "name" : "original_price",
            "type" : "DECIMAL",
            "key" : "original_price"
          }, {
            "name" : "stock",
            "type" : "INT",
            "key" : "stock"
          }, {
            "name" : "low_stock",
            "type" : "INT",
            "key" : "low_stock"
          }, {
            "name" : "unit",
            "type" : "VARCHAR",
            "key" : "unit"
          }, {
            "name" : "weight",
            "type" : "DECIMAL",
            "key" : "weight"
          }, {
            "name" : "brand_name",
            "type" : "VARCHAR",
            "key" : "brand_name"
          }, {
            "name" : "unit_id",
            "type" : "INT",
            "key" : "unit_id"
          } ],
          "connection" : [ {
            "sourceId" : 1,
            "password" : "**",
            "jdbcUrl" : [ "jdbc:mysql://192.168.14.11:3306/biz_dc_test?useSSL=false" ],
            "type" : 1,
            "table" : [ "table_product" ],
            "username" : "aiot"
          } ],
          "sourceIds" : [ 1 ],
          "username" : "aiot"
        },
        "name" : "mysqlreader"
      },
      "writer" : {
        "parameter" : {
          "postSql" : [ ],
          "password" : "**",
          "column" : [ {
            "name" : "id",
            "isPart" : false,
            "type" : "BIGINT",
            "key" : "id"
          }, {
            "name" : "name",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "name"
          }, {
            "name" : "pic",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "pic"
          }, {
            "name" : "product_sn",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "product_sn"
          }, {
            "name" : "delete_status",
            "isPart" : false,
            "type" : "INT",
            "key" : "delete_status"
          }, {
            "name" : "publish_status",
            "isPart" : false,
            "type" : "INT",
            "key" : "publish_status"
          }, {
            "name" : "new_status",
            "isPart" : false,
            "type" : "INT",
            "key" : "new_status"
          }, {
            "name" : "recommand_status",
            "isPart" : false,
            "type" : "INT",
            "key" : "recommand_status"
          }, {
            "name" : "verify_status",
            "isPart" : false,
            "type" : "INT",
            "key" : "verify_status"
          }, {
            "name" : "sort",
            "isPart" : false,
            "type" : "INT",
            "key" : "sort"
          }, {
            "name" : "sale",
            "isPart" : false,
            "type" : "INT",
            "key" : "sale"
          }, {
            "name" : "price",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "price"
          }, {
            "name" : "promotion_price",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "promotion_price"
          }, {
            "name" : "description",
            "isPart" : false,
            "type" : "TEXT",
            "key" : "description"
          }, {
            "name" : "original_price",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "original_price"
          }, {
            "name" : "stock",
            "isPart" : false,
            "type" : "INT",
            "key" : "stock"
          }, {
            "name" : "low_stock",
            "isPart" : false,
            "type" : "INT",
            "key" : "low_stock"
          }, {
            "name" : "unit",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "unit"
          }, {
            "name" : "weight",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "weight"
          }, {
            "name" : "brand_name",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "brand_name"
          }, {
            "name" : "unit_id",
            "isPart" : false,
            "type" : "INT",
            "key" : "unit_id"
          } ],
          "connection" : [ {
            "jdbcUrl" : "jdbc:mysql://192.168.14.11:3306/biz_test?useSSL=false",
            "table" : [ "table_ppp" ]
          } ],
          "sourceIds" : [ 2 ],
          "preSql" : [ ],
          "username" : "aiot"
        },
        "name" : "mysqlwriter"
      }
    } ],
    "setting" : {
      "restore" : {
        "isRestore" : false,
        "isStream" : false
      },
      "speed" : {
        "readerChannel" : 1,
        "writerChannel" : 1,
        "bytes" : -1048576,
        "channel" : 1
      }
    }
  }
}

[15:11:25] <error> 运行失败`

### What you expected to happen

成功运行

### How to reproduce

chunjun有个类型转换异常需要处理

### Version

v1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
使用的chunjun分支是master的吗

**Comment by chirspan** [comment]
遇到相同的问题，flink服务增加配置解决
`# 类加载配置
classloader.resolve-order: parent-first
classloader.check-leaked-classloader: false`

**Comment by Sejon** [comment]
> 是v1.12-SNAPSHOT

**Comment by Sejon** [comment]
> 使用的chunjun分支是master的吗

用的v1.12-SNAPSHOT

**Comment by windwhisper-i** [comment]
> 遇到相同的问题，flink服务增加配置解决 `# 类加载配置 classloader.resolve-order: parent-first classloader.check-leaked-classloader: false`

有截图吗？是在集群配置flink配置中那添加的配置吗？

**Comment by vainhope** [comment]
flink standalone 集群的flink-conf.yml
![image](https://user-images.githubusercontent.com/18212930/211961237-0541182c-3e3f-4c59-ab50-527e50a695b0.png)
