### ISSUE TITLE
[Questions][数据同步]为什么任务实例创建成功之后，等待运行阶段会报错 FLINK 日志如下

### ISSUE THREAD

**Issue by HHXiaoFu** [DTStack/Taier#874]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

同步任务【OA】开始执行
[14:48:58] <info> 已经成功发送执行请求...
[14:48:58] <info> 任务提交成功,名称为: run_sync_task_OA_1668030372193
[14:48:59] <info> 等待运行.....
[14:48:59] <error> 
====================Flink日志====================
2022-11-10 05:46:13:com.dtstack.taier.common.exception.ClientAccessException: Client access exception. 
com.dtstack.taier.common.exception.ClientAccessException: Client access exception. 
	at com.dtstack.taier.common.client.ClientCache.getClient(ClientCache.java:111)
	at com.dtstack.taier.common.client.ClientOperator.judgeSlots(ClientOperator.java:155)
	at com.dtstack.taier.scheduler.WorkerOperator.judgeSlots(WorkerOperator.java:93)
	at com.dtstack.taier.scheduler.WorkerOperator$$FastClassBySpringCGLIB$$b285a6bd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.dtstack.taier.scheduler.WorkerOperator$$EnhancerBySpringCGLIB$$7b22230b.judgeSlots(<generated>)
	at com.dtstack.taier.scheduler.jobdealer.JobSubmitDealer.submitEngineJob(JobSubmitDealer.java:340)
	at com.dtstack.taier.scheduler.jobdealer.JobSubmitDealer.submitJob(JobSubmitDealer.java:329)
	at com.dtstack.taier.scheduler.jobdealer.JobSubmitDealer.lambda$run$0(JobSubmitDealer.java:220)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.dtstack.taier.common.exception.TaierDefineException: java.util.concurrent.ExecutionException: com.dtstack.taier.common.exception.TaierDefineException: com.dtstack.taier.pluginapi.exception.PluginDefineException: Can not find chunjun core jar in path: /usr/local/chunjun-dist
	at com.dtstack.taier.common.client.ClientProxy.init(ClientProxy.java:90)
	at com.dtstack.taier.common.client.ClientCache.getClient(ClientCache.java:102)
	... 23 more
Caused by: java.util.concurrent.ExecutionException: com.dtstack.taier.common.exception.TaierDefineException: com.dtstack.taier.pluginapi.exception.PluginDefineException: Can not find chunjun core jar in path: /usr/local/chunjun-dist
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.dtstack.taier.common.client.ClientProxy.init(ClientProxy.java:86)
	... 24 more
Caused by: com.dtstack.taier.common.exception.TaierDefineException: com.dtstack.taier.pluginapi.exception.PluginDefineException: Can not find chunjun core jar in path: /usr/local/chunjun-dist
	at com.dtstack.taier.common.client.ClientProxy.lambda$init$0(ClientProxy.java:84)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 3 more
Caused by: com.dtstack.taier.pluginapi.exception.PluginDefineException: Can not find chunjun core jar in path: /usr/local/chunjun-dist
	at com.dtstack.taier.flink.config.PluginConfig.getCoreJarPath(PluginConfig.java:106)
	at com.dtstack.taier.flink.config.PluginConfig.getCoreJarInfo(PluginConfig.java:83)
	at com.dtstack.taier.flink.util.FlinkUtil.fillFlinkxToClassLoader(FlinkUtil.java:272)
	at com.dtstack.taier.flink.FlinkClient.init(FlinkClient.java:156)
	at com.dtstack.taier.common.client.ClientProxy$1.execute(ClientProxy.java:79)
	at com.dtstack.taier.common.client.ClientProxy$1.execute(ClientProxy.java:76)
	at com.dtstack.taier.pluginapi.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:31)
	at com.dtstack.taier.common.client.ClientProxy.lambda$init$0(ClientProxy.java:76)
	... 4 more

====================任务信息====================
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "password" : "**",
          "startLocation" : "",
          "increColumn" : "",
          "column" : [ {
            "name" : "id",
            "type" : "VARCHAR",
            "key" : "id"
          }, {
            "name" : "nickname",
            "type" : "VARCHAR",
            "key" : "nickname"
          }, {
            "name" : "job_number",
            "type" : "VARCHAR",
            "key" : "job_number"
          } ],
          "connection" : [ {
            "sourceId" : 1,
            "password" : "**",
            "jdbcUrl" : [ "jdbc:mysql://123.45.xx.xx:3306/oasys" ],
            "type" : 1,
            "table" : [ "taier_tmp1" ],
            "username" : "m8cmp"
          } ],
          "sourceIds" : [ 1 ],
          "username" : "root"
        },
        "name" : "mysqlreader"
      },
      "writer" : {
        "parameter" : {
          "postSql" : [ ],
          "password" : "**",
          "column" : [ {
            "name" : "id",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "id"
          }, {
            "name" : "nickname",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "nickname"
          }, {
            "name" : "job_number",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "job_number"
          } ],
          "connection" : [ {
            "jdbcUrl" : "jdbc:mysql://123.45.xx.xx:3306/oasys",
            "table" : [ "taier_tmp2" ]
          } ],
          "sourceIds" : [ 1 ],
          "preSql" : [ ],
          "username" : "root"
        },
        "name" : "mysqlwriter"
      }
    } ],
    "setting" : {
      "restore" : {
        "isRestore" : false,
        "isStream" : false
      },
      "speed" : {
        "readerChannel" : 1,
        "writerChannel" : 1,
        "bytes" : -1048576,
        "channel" : 1
      }
    }
  }
}

[14:48:59] <error> 运行失败

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HHXiaoFu** [comment]
日志我有看到他说找不到chunjun插件的核心 jar 包 ，但是事实上地址是存在该jar 的

**Comment by vainhope** [comment]
core.jar 是找的taier本服务器的jar
如果是docker部署的话 需要将chunjun 和flink的目录映射到docker内

**Comment by HHXiaoFu** [comment]
> core.jar 是找的taier本服务器的jar 如果是docker部署的话 需要将chunjun 和flink的目录映射到docker内

感谢，已经解决啦
