### ISSUE TITLE
MySQL到Kafka数据同步任务报错

### ISSUE THREAD

**Issue by Yinyuhang123** [DTStack/Taier#974]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

同一个MySQL到Kafka的job.json，chunjun中可以提交并执行，taier却显示提交失败
chunjun提交图
![chunjun执行](https://user-images.githubusercontent.com/116626639/215935539-78a32706-8f21-4191-8125-c79c66d804a1.jpg)
kafka消费图
![image](https://user-images.githubusercontent.com/116626639/215935629-f980f422-dc10-4b52-a3f9-a44b54eb9e0d.png)
taier提交失败图
![8ef6b62a3412725e32446838485a7c3](https://user-images.githubusercontent.com/116626639/215935664-ac06bd36-e82e-4d7f-8ace-7b68e4c7970f.png)

任务日志taier.log
2023-02-01 11:18:29.981 [http-nio-8090-exec-5] INFO  org.springframework.web.servlet.DispatcherServlet [FrameworkServlet.java:547] - Completed initialization in 13 ms
2023-02-01 11:19:07.390 [http-nio-8090-exec-1] WARN  c.d.t.d.service.develop.impl.DevelopJobService [DevelopJobService.java:127] - startSyncImmediately-->
com.dtstack.taier.common.exception.TaierDefineException: 创建数据同步job失败: null
	at com.dtstack.taier.develop.service.develop.runner.SyncTaskRunner.readyForSyncImmediatelyJob(SyncTaskRunner.java:128)
	at com.dtstack.taier.develop.service.develop.impl.DevelopJobService.startSyncImmediately(DevelopJobService.java:106)
	at com.dtstack.taier.develop.controller.develop.DevelopJobController$1.process(DevelopJobController.java:58)
	at com.dtstack.taier.develop.controller.develop.DevelopJobController$1.process(DevelopJobController.java:54)
	at com.dtstack.taier.common.lang.coc.APITemplate.execute(APITemplate.java:107)
	at com.dtstack.taier.develop.controller.develop.DevelopJobController.startSyncImmediately(DevelopJobController.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dtstack.taier.develop.filter.DtRequestWrapperFilter.doFilterInternal(DtRequestWrapperFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at com.dtstack.taier.develop.service.develop.runner.SyncTaskRunner.addConfPropAndParseJob(SyncTaskRunner.java:164)
	at com.dtstack.taier.develop.service.develop.runner.SyncTaskRunner.readyForSyncImmediatelyJob(SyncTaskRunner.java:115)
	... 51 common frames omitted

任务json
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "password": "lovol",
            "startLocation": "",
            "increColumn": "",
            "column": [
           *
            ],
            "connection": [
              {
                "sourceId": 1,
                "password": "123456",
                "jdbcUrl": [
                  "jdbc:mysql://localhost:3306/test?characterEncoding=utf8&autoReconnect=true"
                ],
                "type": 1,
                "table": [
                  "l_biz_data_202212test"
                ],
                "username": "root"
              }
            ],
            "sourceIds": [
              1
            ],
            "username": "root"
          },
          "name": "mysqlreader"
        },
        "writer": {
          "parameter": {
            "tableFields": [
            *
            ],
            "topic": "m2k",
            "producerSettings": {
              "auto.commit.enable": "false",
              "bootstrap.servers": "master:9092,slave1:9092,slave2:9092"
            }
          },
          "name": "kafkawriter"
        }
      }
    ],
    "setting": {
      "restore": {
        "isRestore": true,
        "isStream": true
      },
      "speed": {
        "readerChannel": 1,
        "writerChannel": 1
      }
    }
  }
}

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QAQ-Jun** [comment]
![image](https://user-images.githubusercontent.com/33590567/215938002-96f0678a-e913-48a9-bd52-2ec3fd99d847.png)
现在出问题的地方，是chunjun最新版本支持读写并行度分开设置，但是taier代码逻辑还没有兼容chunjun这块最新的逻辑

目前临时解决可以先把"speed": {
"readerChannel": 1,
"writerChannel": 1
} 设置成"speed": {
"channel": 1
}

**Comment by Yinyuhang123** [comment]
感谢
