### ISSUE TITLE
taier1.3数据同步 java.lang.ClassNotFoundException: ch.qos.logback.classic.Logger

### ISSUE THREAD

**Issue by zqsgithub2023** [DTStack/Taier#985]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

![image](https://user-images.githubusercontent.com/125441824/219563254-e8afce99-3103-48b5-bc97-7e8e9d6df583.png)
任务能提交到flink集群上，就是报org.apache.flink.runtime.client.JobInitializationException: Could not instantiate JobManager.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
报错可以贴详细点么
flink standalone的集群嘛

**Comment by zqsgithub2023** [comment]
我是布置一个单机版的flink1.12.7，chunjun 用的最新发行版本1.27。
![image](https://user-images.githubusercontent.com/125441824/219991077-7d35bf27-532a-4f4b-b983-df8a714b7057.png)
flink的配置也添加了
classloader.resolve-order: parent-first 
classloader.check-leaked-classloader: false
最后就是通过taier 提交任务，任务到flink 就报
![image](https://user-images.githubusercontent.com/125441824/219991615-f8abaefb-eb3d-4ad4-9501-59f1f1d371d4.png)
taier里的flink配置如下
![image](https://user-images.githubusercontent.com/125441824/219991572-337452b7-7b48-4118-adec-d49fd34faf0e.png)

**Comment by zqsgithub2023** [comment]
同步任务【同步数据】开始执行
[09:57:44] <info> 已经成功发送执行请求...
[09:57:44] <info> 任务提交成功,名称为: run_sync_task_同步数据_1676858263335
[09:57:45] <info> 等待运行.....
[09:57:47] <info> 等待运行.....
[09:57:48] <info> 等待运行.....
[09:57:50] <info> 等待运行.....
[09:57:52] <info> 等待运行.....
[09:57:53] <info> 等待运行.....
[09:57:55] <info> 等待运行.....
[09:57:55] <error> 
====================Flink日志====================
org.apache.flink.runtime.client.JobInitializationException: Could not instantiate JobManager.
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Source: mysqlsourcefactory -> Sink: mysqlsinkfactory': Loading the input/output formats failed: 
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:293)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createExecutionGraph(SchedulerBase.java:322)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:276)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:249)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:133)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:111)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:342)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:327)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:95)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:39)
	at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:163)
	at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:86)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:472)
	... 4 more
Caused by: java.lang.Exception: Loading the input/output formats failed: 
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:172)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:57)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:289)
	... 16 more
Caused by: java.lang.RuntimeException: Deserializing the input/output formats failed: Could not read the user code wrapper: ch.qos.logback.classic.Logger
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:69)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:168)
	... 18 more
Caused by: org.apache.flink.runtime.operators.util.CorruptConfigurationException: Could not read the user code wrapper: ch.qos.logback.classic.Logger
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:307)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:66)
	... 19 more
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:76)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2011)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1875)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2209)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at java.util.HashMap.readObject(HashMap.java:1418)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2345)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:615)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:600)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:587)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:541)
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:304)
	... 20 more

2023-02-20 09:57:53:submit job is success
====================任务信息====================
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "password" : "**",
          "startLocation" : "",
          "increColumn" : "",
          "column" : [ {
            "name" : "id",
            "type" : "INT UNSIGNED",
            "key" : "id"
          }, {
            "name" : "classify_code",
            "type" : "VARCHAR",
            "key" : "classify_code"
          }, {
            "name" : "sorted",
            "type" : "INT",
            "key" : "sorted"
          }, {
            "name" : "classify_name",
            "type" : "VARCHAR",
            "key" : "classify_name"
          }, {
            "name" : "is_deleted",
            "type" : "TINYINT",
            "key" : "is_deleted"
          }, {
            "name" : "gmt_create",
            "type" : "DATETIME",
            "key" : "gmt_create"
          }, {
            "name" : "gmt_modified",
            "type" : "DATETIME",
            "key" : "gmt_modified"
          } ],
          "connection" : [ {
            "sourceId" : 1,
            "password" : "**",
            "jdbcUrl" : [ "jdbc:mysql://192.168.168.200:3306/iccm_ermp" ],
            "type" : 1,
            "table" : [ "datasource_classify" ],
            "username" : "root"
          } ],
          "sourceIds" : [ 1 ],
          "username" : "root"
        },
        "name" : "mysqlreader"
      },
      "writer" : {
        "parameter" : {
          "postSql" : [ ],
          "password" : "**",
          "column" : [ {
            "name" : "id",
            "isPart" : false,
            "type" : "INT UNSIGNED",
            "key" : "id"
          }, {
            "name" : "classify_code",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "classify_code"
          }, {
            "name" : "sorted",
            "isPart" : false,
            "type" : "INT",
            "key" : "sorted"
          }, {
            "name" : "classify_name",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "classify_name"
          }, {
            "name" : "is_deleted",
            "isPart" : false,
            "type" : "TINYINT",
            "key" : "is_deleted"
          }, {
            "name" : "gmt_create",
            "isPart" : false,
            "type" : "DATETIME",
            "key" : "gmt_create"
          }, {
            "name" : "gmt_modified",
            "isPart" : false,
            "type" : "DATETIME",
            "key" : "gmt_modified"
          } ],
          "connection" : [ {
            "jdbcUrl" : "jdbc:mysql://192.168.168.200:3306/iccm_ermp",
            "table" : [ "bakdatasource_classify" ]
          } ],
          "sourceIds" : [ 1 ],
          "preSql" : [ ],
          "username" : "root"
        },
        "name" : "mysqlwriter"
      }
    } ],
    "setting" : {
      "restore" : {
        "isRestore" : false,
        "isStream" : false
      },
      "speed" : {
        "readerChannel" : 1,
        "writerChannel" : 1,
        "bytes" : -1048576,
        "channel" : 1
      }
    }
  }
}

[09:57:55] <error> 运行失败

**Comment by zqsgithub2023** [comment]
问已经解决了，少了ogback-core-1.2.11.jar ；logback-classic-1.2.11.jar 个包，从网上https://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.2.11 下载的。

**Comment by bnyte** [comment]
数据同步报错QA#260

**Comment by peterfei** [comment]
> 问已经解决了，少了ogback-core-1.2.11.jar ；logback-classic-1.2.11.jar 个包，从网上https://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.2.11 下载的。

你好，麻烦问下，这个包是放在哪的？
